### ISSUE TITLE
navigator.serviceWorker.controller always remains null

### ISSUE THREAD

**Issue by iiison** [GoogleChrome/sw-precache#104]
I was trying to cache some files, I did following:

Gulp Task:
```javascript
gulp.task('generate-service-worker', function(callback) {
        // basepath is global variable with value: 'public/mobile'
	var swPrecache = require('sw-precache');
	swPrecache.write(basePath+ '/sw.js', {
		"staticFileGlobs": [
			basePath + "/stylesheets/css/new/**.css",
			basePath + "/images/**.*",
			basePath + "/fonts/**.*",
			basePath + "/build/javascripts/dist/**.js",
			basePath + "/javascripts/s_code.js",
		],
		stripPrefix: "public/mobile/"
	}, callback)
});
```

Here is how I am registering the serviceworker:
```javascript
if ('serviceWorker' in navigator) {
    navigator.serviceWorker.register('/mobile/sw.js', {scope: '/mobile/'}).then(function(reg) {
    console.log(reg);
    if(!navigator.serviceWorker.controller){
        console.info("controller is still none for some reason.");
        return;
    }
    console.log("worker is registered properly!");
}).catch(function (err) {
    console.error("Something is not right, worker wasn't registered");
    console.log(err);
});
```

I am using node(express), this is file structure:

```
├── bin
├── models
├── routes
├── views
├──┬─ public
│  └─┬─ mobile
│    ├── css
│    ├── js
│    ├── fonts
│    ├── images
│    ├── sw.js
│    └── manifest.json
... and some other files
directory structure of public directory is like public > mobile > all files including css, sw.js
```

The URL from where my index page is served is: localhost:3000/mobile.

The problem is navigator.serviceWorker.controller always remains null, I am not sure what am I missing here.

Let me know if you need anything else to get more info.

**Comment by jeffposnick** [comment]
There's an expected gap in time between when the `register()` call resolves and when the service worker takes control of your page.

Are you checking the `navigator.serviceWorker.controller` value just for your own reassurance, or is there something specific that you need to do when the service worker takes control?

A general pattern that I can recommend is to listen to changes in the service worker lifecycle from your page and then hook into those to, e.g., notify the user when the caches are populated or when the caches are updated. Because those rely on listening for specific events, they deal gracefully with the gap in time between the registration and the service worker taking control. You can see an example at https://github.com/GoogleChrome/sw-precache/blob/master/demo/app/js/service-worker-registration.js#L25

**Comment by iiison** [comment]
@jeffposnick , I am trying to load new `servicewroker` when I make some changes. The issue I was facing previously was, I was loading it at page `localhost:3000/mobile`, instead of that I was supposed to add one more slash(localhost:3000/mobile/), it was because of scope issue.

My current problem is that I am not able update my `serviceworker`. I followed the link you mentioned in your answer and here how I am tracing the statechange:

```javascript
if(reg.installing){
	reg.installing.onstatechange = function(event) {
		if (this.state === 'installed') {
			console.log("new sw is activated now.");
		}
	};
}
if(!navigator.serviceWorker.controller){
	console.info("controller is still none for some reason.");
	return;
}
if(reg.waiting){
	console.log("worker was waiting");
	that.updateReady(reg.waiting);
	return;
}
````

I updated few lines in serviceworker, but control never comes in `reg.waiting` or `reg.installing`. I also tried to debug it through the dev tools, waiting tab always stays disabled.

**Comment by rossta** [comment]
@iiison Have you tried any or all of the following?

* Close and reopen the tab to allow the new serviceworker to take control
* Insert `self.skipWaiting` in your serviceworker to allow it to be activated
* Use Chrome Canary and enable "Update on reload" in the Resources > Service Worker inspector pane

![wittr](https://cloud.githubusercontent.com/assets/11673/14712597/c6c3d140-07ab-11e6-8741-adb90b4f725e.jpg)

**Comment by iiison** [comment]
@rossta I agree that close and reopen will take control eventually. I need to delete the old cache when new serviceworker take control.How do I do that. I can't use update on reload on production code.

**Comment by jeffposnick** [comment]
If you're using `sw-precache`, you shouldn't have to worry about manually managing your caches. They files that `sw-precache` picks up will automatically be versioned, and old entries will be swapped out for new ones. That's the reason to use `sw-precache` to begin with.

`sw-precache` automatically includes `skipWaiting()` as part of its `install` handler, so its SW should never end up in the `waiting` state.

**Comment by iiison** [comment]
@jeffposnick but the size of my cache is keep increasing. It's almost 17mb from 260kb.

**Comment by jeffposnick** [comment]
`sw-precache` only adds the files that match the configuration patterns to its cache, and only does that during the `install` handler. Once the SW is installed, it's not going to add anything else to the cache.

Are you also using a runtime SW caching library, like `sw-toolbox`? And how are you determining what the current size of the cache is?

**Comment by iiison** [comment]
Chrome shows the cache size when you try to delete it.

**Comment by jeffposnick** [comment]
I believe that will include the "normal" browser HTTP cache in addition to the caches that are explicitly managed by the Cache Storage API via the SW.

**Comment by iiison** [comment]
ok, I agree with that.. but I am not able to see my latest changes after deployment. I have to hard refresh to see the changes. Even after the hard refresh, if I do normal refresh I can't see my changes. I've to explicitly delete the serviceworker to populate my changes. How do i fix that..

**Comment by rossta** [comment]
Possibly one other thing to check: is your server cache request headers on your serviceworker script, e.g. `Expires` and/or `Cache-Control`? I believe the general recommendation is to instruct browsers not to cache your serviceworker scripts with `must-revalidate`, `max-age=0`, etc.

**Comment by iiison** [comment]
yes, it is `Cache-Control:public, max-age=31536000`, How do i make it 0??

**Comment by iiison** [comment]
@rossta @jeffposnick any idea how to change change max-age header for sw.js file

**Comment by rossta** [comment]
It will depend on your app server (Node, Rails, etc) and/or your web server (nginx, Apache) and possibly other servers sitting between your app and the client (like a CDN).

**Comment by iiison** [comment]
I did some research, turns out we are setting max-age to 365 days to static files. We are using node(express), I changed it my app.js this:
```javascript
app.use(express.static(path.join(__dirname, 'public'),{
  redirect : false,
  maxAge : '365 days',
  setHeaders : function(res,path){
    if(path.indexOf('service-worker.js')!=-1){
      res.setHeader('Cache-Control','public, max-age=0')
    }
  }
}));
```

But the file is still getting served from the cache. Is there any other way to reset the header..

**Comment by rossta** [comment]
I'm not sure which "cache" you mean. If you mean the browser cache, a hard refresh should be enough to clear the cache and get the browser to honor the new response headers. As for your header override, you could try:

```javascript
res.setHeader('Cache-Control', 'private, max-age=0, no-cache');
```

**Comment by jeffposnick** [comment]
I'm closing this, as I don't believe there's anything to be done on the `sw-precache` front.

**Comment by chinchang** [comment]
Try adding this in the service worker:

```
self.addEventListener('activate', event => {
	clients.claim();
	console.log('Ready!');
});
```
