### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by wibblymat** [GoogleChrome/sw-precache#115]
Looks like #110 fixes #108, but there hasn't been a release since it landed.

CC: @agektmr

**Comment by jeffposnick** [comment]
Sorry, yes, I was holding off before I/O but I do plan on cutting a new release this week to pick up a few fixes.

**Comment by jeffposnick** [comment]
https://github.com/GoogleChrome/sw-precache/releases/tag/3.2.0 is out.

**Comment by agektmr** [comment]
awesome!
