### ISSUE TITLE
Replace Fingerprint in path of published file to hit the cache

### ISSUE THREAD

**Issue by ri-gr** [GoogleChrome/sw-precache#117]
Hi, i have the challenge that i have the following fingerprinted urls in the produtive environment

`/static/vd74f97c0d457e47c2127e29658e7a13f/release/styles.min.css`

These paths are generate serverside during runtime and on request the md5-sum gets replaced by a serversider rewrite rule so it returns the file located in the physical path without the part of the md5 sum:

`/static/release/styles.min.css`

the precached version of the SW does not hit the cache as the producitve path does not match with the precached generated path.

Is there a way to use any of the options to work around that without modifying the generated service worker?

Unfortunately the replacePrefix  does not provide a Regex syntax.

**Comment by jeffposnick** [comment]
If you're using `sw-precache` along with the [App Shell model](https://developers.google.com/web/updates/2015/11/app-shell), you will (usually) end up not having to contact your server at all when requesting local resources like CSS files once the service worker is installed.

This means that you should cache an App Shell HTML document that includes a reference to the specific CSS URL that's also going to be available in your cache. This cached HTML can be different from the HTML that's returned for non-SW navigation requests by your server, and you can use the [`navigateFallback`](https://github.com/GoogleChrome/sw-precache#navigatefallback-string) option to ensure that all navigation requests are redirected to your App Shell HTML, regardless of what the navigation URL is.

This [presentation](https://speakerdeck.com/jeffposnick/instant-loading-with-service-workers-chrome-dev-summit-15) gives more background on this approach, and includes references to a [demo](https://github.com/GoogleChrome/sw-precache/tree/master/app-shell-demo) that has versioned subresources.

**Comment by ri-gr** [comment]
Thanks for your feedback but i cannot use the approach from the demo as my files are not physically renamed in the filesystem and therefore cannot be used by sw-precache on generating the service worker. The virtual path is generated by the webserver during runtime. Which means the files cached by the service worker will never be used as the files referenced by the html returned from the web-server do not match with their path.

sw-precache is using: `/static/release/styles.min.css`
html is referencing: `/static/vd74f97c0d457e47c2127e29658e7a13f/release/styles.min.css`
