### ISSUE TITLE
Cannot use basic routing

### ISSUE THREAD

**Issue by wernight** [GoogleChrome/sw-precache#129]
Example of a Gulp file:

    runtimeCaching: [{
        urlPattern: '/',
        handler: 'networkFirst'
    }],

This generates a service-worker.js with:

    toolbox.router.get(/, toolbox.networkFirst, {});

`/` isn't a string and it generates a runtime error. The README of sw-precache however states that it can be a string, hinting that it would behave like sw-toolbox string routing. Either case '/' should become either: `'/'` or `/\//` and the README should be clarified.

**Comment by jeffposnick** [comment]
Sorry about that. See https://github.com/GoogleChrome/sw-precache/issues/108.
