### ISSUE TITLE
Unexpected token with custom tmpl file

### ISSUE THREAD

**Issue by ihsansatriawan** [GoogleChrome/sw-precache#132]
Hi,

I want to use `templateFilePath` to target my modify `service-worker.tmpl`, i have tried write in config
`templateFilePath: _.template(require('./src/browser/service-worker-modify.tmpl'))` but it's throw error `Unexpected token` for `<% if (handleFetch && swToolboxCode) { %>`, how can i solved this ? thx

**Comment by jeffposnick** [comment]
The `templateFilePath` is intended to be a path to a file, not the contents of the file.

With your custom path, try the following:

```js
templateFilePath: './src/browser/service-worker-modify.tmpl'
```
