### ISSUE TITLE
App runing in nested directories- 404 error

### ISSUE THREAD

**Issue by Pirozek** [GoogleChrome/sw-precache#135]
Hi, I am trying to use `sw-precache` but I cant figure out how to tell the worker url of my website. On localhost I use directories for different clients, so my project is not running on something like `http://localhost/index.html` but more like `http://localhost/client1/projectA/dist/index.html`, but worker still try to cache files from just `localhost` like `GET http://localhost/404.html?sw-precache=ca4e20c45a973165115efeb4fe699951 404 (Not Found)` which should look like `GET http://localhost/client1/projectA/dist/404.html?sw-precache=ca4e20c45a973165115efeb4fe699951 404 (Not Found)`

Is there any option or setting that I am missing?

**Comment by jeffposnick** [comment]
`sw-precache` uses relative URLs for the resources it manages. Those relative URLs are resolved into absolute URLs using the location of the service worker JavaScript file as the base.

The easiest approach, based on what you describe, would be to make sure to serve the generated service worker JavaScript file from the top-level directory that's specific to your given project. This also follows the best-practices for service worker scoping, and allows you to host multiple service workers on the same web server without their scopes overlapping.

So in your example, you'd want to serve your service worker JavaScript from the URL `http://localhost/client1/projectA/dist/service-worker.js`, and then when it tries to fetch, e.g., `404.html`, that relative URL will automatically be resolved to the full URL `http://localhost/client1/projectA/dist/404.html`.

**Comment by Pirozek** [comment]
Ok, so instead of loading it like:
```if ('serviceWorker' in navigator) {
        navigator.serviceWorker.register('service-worker.js');
    }```

I am loading worker like this:
```
if ('serviceWorker' in navigator) {
        navigator.serviceWorker.register('http://localhost/client1/projectA/dist/service-worker.js');
    }
```

And it still tries to load things from `localhost/file` instead of `localhost/client1/.../file`, is there anything else I am missing?

**Comment by jeffposnick** [comment]
Could you pass along the `sw-precache` configuration options that you're using?

**Comment by Pirozek** [comment]
Ok I fixed it, problem was in `stripPrefix` where I had one `\` that wasnt supposed to be there :)
