### ISSUE TITLE
500 Service Worker Response Error

### ISSUE THREAD

**Issue by Viktori** [GoogleChrome/sw-precache#137]
I am using runtimeCaching but sometimes see random 500 Service Worker Response Error (in online mode).
Maybe I just missing some options or settings?

**Comment by jeffposnick** [comment]
It's hard to say—can you provide a public URL and steps to reproduce the issue?

If for some reason you can't, then it would be good to know whether there's anything logged in the JavaScript console in your browser associated with the HTTP 500 response.

**Comment by ladariha** [comment]
For what it's worth, I'm seeing random SW worker response errors in Chrome. No idea if releated, I apologize if not. I've made reproducible test case (see https://bugs.chromium.org/p/chromedriver/issues/detail?id=1413)

**Comment by jeffposnick** [comment]
As it stands, I don't think there's anything actionable related to `sw-precache` in this issue. If there's some more information about steps to reproduce and a public URL that you can provide, @Viktori, please re-open and I'm happy to investigate further.

**Comment by Joeycz** [comment]
have any idea, I met the same problem, random 500, the get assets fail

**Comment by iceshu** [comment]
me too
