### ISSUE TITLE
stripPrefix doesn't support regex

### ISSUE THREAD

**Issue by cdbattags** [GoogleChrome/sw-precache#141]
Why does it not?

My use case:

I have a big array for staticFileGlobs and I need to match a specific regex to strip all prepended path for specific modules held at certain levels in the hierarchy.

**Comment by cdbattags** [comment]
see pr #142

**Comment by grri** [comment]
also replacePrefix should support a Regex - that would help me for my usecase #117

**Comment by TimvdLippe** [comment]
I think this has been fixed in #138?

**Comment by jeffposnick** [comment]
Yes, I believe it is. Please reopen if the latest `sw-precache` release doesn't resolve the issue for you.
