### ISSUE TITLE
Relax top-level service worker requirement

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/sw-precache#147]
As per https://github.com/slightlyoff/ServiceWorker/issues/839#issuecomment-236259645, it sounds like the service worker specification will be updated to allow any byte-by-byte changes to `importScripts()` resources to trigger the Install flow. This opens the door towards allowing developers to pull in `sw-precache`'s output via `importScripts()` instead of forcing them to use it as their top-level service worker.

It also might open the door to some of the refactoring that @gauntface has advocated for in https://github.com/GoogleChrome/sw-precache/issues/43 and elsewhere.

This all will depend on browsers shipping service worker implementations that adhere to the new behavior, so this issue is more of a long-term reminder than anything immediately actionable.

CC: @addyosmani @wibblymat

**Comment by gauntface** [comment]
This is very exciting :)

**Comment by addyosmani** [comment]
👍 . @jeffposnick I wasn't able to locate a Chromium bug on the related ServiceWorker thread to track when we might be able to switch to the ideas in #43. Do you know if one has been filed yet?

**Comment by jeffposnick** [comment]
I haven't seen one. I'll ask around internally to make sure it's on the Chrome engineering team's radar.

**Comment by jeffposnick** [comment]
The pre-requisite functionality is tracked in Chrome at https://bugs.chromium.org/p/chromium/issues/detail?id=648295
and in Firefox at https://bugzilla.mozilla.org/show_bug.cgi?id=1290951

**Comment by jeffposnick** [comment]
Developers who need this functionality are encouraged to migrate to https://workboxjs.org/

That has superseded any plans to rewrite `sw-precache` to add in this functionality.
