### ISSUE TITLE
Failed to parse SourceMap

### ISSUE THREAD

**Issue by LandonSchropp** [GoogleChrome/sw-precache#148]
I'm running into an issue when trying to create a service worker for my CDN assets. Here's what my Gulp task looks like:

```
'use strict'

const gulp = require('gulp')
const swPrecache = require('sw-precache')

const runtimeCaching = [
  {
    urlPattern: /^https:\/\/cdnjs\.cloudflare\.com/,
    handler: 'networkFirst'
  }
]

gulp.task('serviceWorker', (callback) => {
  swPrecache.write("build/service_worker.js", { runtimeCaching }, callback)
})
```

When I load the service worker into my browser, I get this error:

```
Failed to parse SourceMap: http://localhost:3000/build/sw-toolbox.map.json
```

Issue #93 seems related, but it's closed and I'm still seeing this issue with 4.0.0. Is there some way to turn off the source map or to generate the source map to get this error to go away?

**Comment by jeffposnick** [comment]
I'm closing this in favor of https://github.com/GoogleChrome/sw-toolbox/issues/169
