### ISSUE TITLE
CLI access

### ISSUE THREAD

**Issue by bevacqua** [GoogleChrome/sw-precache#16]
Most major tools in this area have a CLI counterpart. It'd be great to have a CLI for `sw-precache` as well.

**Comment by jeffposnick** [comment]
I hadn't previously considered it.

Could you give me some background on what the use case would be and the type of output you'd expect from running a CLI version?

**Comment by bevacqua** [comment]
# CLI API

## precache <file> <file> <file>

```shell
precache **/*.{js,html,css,png,jpg,gif}
```

Prints the result of doing the following to the standard output.

```shell
var rootDir = process.cwd();
swPrecache({
  staticFileGlobs: [rootDir + '/**/*.{js,html,css,png,jpg,gif}'],
  stripPrefix: rootDir
}, function (err, result) {
  if (err) {
    console.error(err); process.exit(1);
  } else {
    console.log(result);
  }
});
```

## precache <file> <file> <file> --output <dest>

Redirects result to `dest`. Effectively the same as `precache <file> <file> <file> > dest`. `-o` as a shorthand for `--output`

**Comment by jeffposnick** [comment]
I've put together something preliminary at https://github.com/GoogleChrome/sw-precache/tree/cli

If you feel comfortable trying that out prior to official release, please pass along any feedback. Otherwise, I'll merge things into master and cut a new release in a couple of days.

**Comment by jeffposnick** [comment]
@bevacqua curious as to whether that's what you had in mind.

**Comment by bevacqua** [comment]
LGTM. Should probably be mentioned somewhere in documentation too

**Comment by jeffposnick** [comment]
Thanks for the original suggestion, @bevacqua. Obviously took some time before I ended up releasing it, but I hope it will end up being a useful initial implementation.
