### ISSUE TITLE
Service worker not loading Favicon from cache.

### ISSUE THREAD

**Issue by jasan-s** [GoogleChrome/sw-precache#161]
Devtools confirms that favion.ico is cached , yet on each reload the favicon is loaded from network not cache

**Comment by jeffposnick** [comment]
That's unfortunately not something that `sw-precache` has any control over. I assume you're seeing this in Chrome (I don't know how Firefox behaves), but yeah Chrome's requests for the favicon don't trigger the `fetch` event handler in the active service worker.

The Chrome bug tracking this is https://bugs.chromium.org/p/chromium/issues/detail?id=448427
