### ISSUE TITLE
How to config if my site was serve on github pages

### ISSUE THREAD

**Issue by markhuang1212** [GoogleChrome/sw-precache#163]
for example, my site 'root path' in in abc.github.io/project/ , i can register the service worker by `navigator.serviceWorker.register('/project/service-worker.js');`, but service worker won't cache the file properly.

**Comment by jeffposnick** [comment]
The demo in this repo, https://github.com/GoogleChrome/sw-precache/tree/master/demo, works with a `gh-pages` deployment.

You can see it served live at https://googlechrome.github.io/sw-precache/ and the configuration used for that deployment is at https://github.com/GoogleChrome/sw-precache/blob/master/demo/gulpfile.js#L37

Does that help?

**Comment by jeffposnick** [comment]
(I'm going to close this but feel free to re-open if that doesn't help.)

**Comment by markhuang1212** [comment]
Thanks, and it helps me a lot @jeffposnick
