### ISSUE TITLE
Revamp the names of confusing options

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/sw-precache#164]
There are a few options whose names made sense to me initially, but are in retrospect not carefully named. I'd like to start by adding in aliases for those options, keeping the old ones functional but logging a deprecation message during build time. And then theoretically remove them in the next major revision. (Or keep them working, but remove them from the documentation?)

I was thinking of the following, and I'm open to suggestions:
- `staticFileGlobs` ⇒ `filesToCache`
- `dynamicUrlToDependencies` ⇒ `serverRenderedUrls`
- `navigateFallback` ⇒ `defaultRoute`
- `navigateFallbackWhitelist` ⇒ `defaultRouteWhitelist`
- `replacePrefix`, `stripPrefix`, `stripPrefixMulti` ⇒ try to wrap these up into a single `modifyUrlPrefix` option

CC: @addyosmani @gauntface @jpmedley for thoughts.

**Comment by jpmedley** [comment]
I like all of these except for the navigateFallback and
navigateFallbgackWhitelist.

If I were completely new to the tool, I may not know what a route is. But I
can work out what navigateFallback probably is.

Joe Medley | Technical Writer, Chrome DevRel | jmedley@google.com |
 816-678-7195
*If an API's not documented it doesn't exist.*

**Comment by jpmedley** [comment]
In other words, an option that explains itself is better than one I have to
read about.

Joe Medley | Technical Writer, Chrome DevRel | jmedley@google.com |
 816-678-7195
*If an API's not documented it doesn't exist.*

**Comment by jeffposnick** [comment]
Thanks, @jpmedley. I can leave `navigateFallback` as-is.

Longer-term, I want to address routing to multiple App Shells via #94, at which point including routing in a parameter name might make sense.

**Comment by jasan-s** [comment]
I like the change in name.

**Comment by addyosmani** [comment]
I like the renames. I'm personally also fine with:

- `navigateFallback` ⇒ `defaultRoute`
- `navigateFallbackWhitelist` ⇒ `defaultRouteWhitelist`

But if consensus is a first time user is going to find it straight-forward to understand what these do as-is then let's for sure keep them as is.

**Comment by gauntface** [comment]
Probably just me but I'd understand what  is intended with 'serverRenderedUrls' if it included the term 'template' somewhere in the name.

'templatesToUrls' would make sense to me more immediately than 'serverRenderedUrls'.

**Comment by jeffposnick** [comment]
`templatesToUrls` sounds like a mapping in which each key is a template, and the values are one or more URLs. That doesn't reflect what's being configured here.

Including "template" in the name sounds good, so how about `templatedUrls`?

While I normally use *abcToXYZ* to name variables that represent mappings, that's not a hard and fast convention.

**Comment by gauntface** [comment]
@jeffposnick sounds better than my suggestion :+1:

**Comment by addyosmani** [comment]
Echoing further support for `templatedUrls`. I think that's a lot more sensible a name to move forward on.

**Comment by jeffposnick** [comment]
We've switched to improved names for a number of similar parameters in https://workboxjs.org/

Making a breaking change to rename the options in `sw-precache` isn't a priority.
