### ISSUE TITLE
sw precache and onesignal conflict

### ISSUE THREAD

**Issue by jasan-s** [GoogleChrome/sw-precache#169]
I wanted to use onesignal for webpush but it requires to load their js files and register their service worker (which overwrites any active service workers). I was told to use import scripts  to load my custom logic(sw-precache generated file) in to onesignal service worker file , however, this makes the onesignal service worker the active service worker thus any changes on my file hashes doesnt trigger a update.

**Comment by jeffposnick** [comment]
I'm not familiar with OneSignal.

Could you share a link to the documentation for the service that you're using, including any samples of how they recommend integration and what their service worker looks like?

**Comment by jasan-s** [comment]
Jeff here it is, the files. Are on the same page: https://documentation.onesignal.com/docs/website-sdk-installation.

**Comment by addyosmani** [comment]
@jasan-s Would you happen to have a minimal sample of where you're trying to use OneSignal with sw-precache available? It might be helpful for us to expedite suggestions on the issue.

**Comment by jeffposnick** [comment]
I see a reference to

- https://cdn.onesignal.com/sdks/OneSignalSDK.js
- https://cdn.onesignal.com/OneSignalSDKUpdaterWorker.js

on the page you linked, to @jasan-s. After unminifying that JavaScript, neither file seems to be the top-level service worker code that you're supposed to pass to `navigator.serviceWorker.register()`. Based on what you said initially, the incompatibility was with that top-level JavaScript file.

**Comment by jasan-s** [comment]
I looked through the OneSignalSDK.js as well  and it does seem to implement a code to register a SW. see here on this [gist](https://gist.github.com/jasan-s/0c9c2ba4b8340579000a7f62bb3f7a1c#file-gistfile1-txt-L4736-L4738). OneSignal instructions also state to Upload the files(OneSignalSDKWorker.js & OneSignalSDKUpdaterWorker.js) to the top-level root of your site directory.

**Comment by jeffposnick** [comment]
I'm not referring to the code that calls `navigator.serviceWorker.register()`. I'm referring to not knowing what the actual top-level service worker code that OneSignal requires is (i.e., the contents of the file that *gets* registered). It's referred to in that gist as `t + e.SERVICE_WORKER_UPDATER_PATH`, but I don't know what's contained in that file.

**Comment by jeffposnick** [comment]
Ping to @jasan-s to see if this is still an issue, and if so, whether you can provide the information requested in my last comment.

**Comment by jasan-s** [comment]
@jeffposnick  I have instead successfully using FCM now.

**Comment by jeffposnick** [comment]
Good to hear!
