### ISSUE TITLE
using navigatefallback causes Uncaught SyntaxError: Unexpected token < 

### ISSUE THREAD

**Issue by jasan-s** [GoogleChrome/sw-precache#171]
I used navigateFallback : 'index.html' since I'm working with a SPA using react-router with browser history. However, when i did , it seems its effecting the facebook login button which causes errors. IF i remove navigate fallback option, the facebook login works fine. How do i blacklist the fallback so the facebook login works fine.

**Comment by jeffposnick** [comment]
There is no blacklist for `navigateFallback`. What you can do instead is whitelist patterns of URLs that you do want matched, using [`navigateFallbackWhitelist`](https://github.com/GoogleChrome/sw-precache#navigatefallbackwhitelist-arrayregexp).

The exact configuration you'd want really depends on your web app's URLs, but in general, try to use a RegExp that matches the minimal set of possible routes.
