### ISSUE TITLE
PWA launched from home screen does not register a update ever unless user clears cache or reloads!

### ISSUE THREAD

**Issue by jasan-s** [GoogleChrome/sw-precache#172]
I want to confirm this behavior its the same for a tab open browser. As long as user has that tab open or launched from home screen and either does not close the tab or just launched from home screen without clearing cache. The service worker will never register that there is new content. IF they do clear cache or close tab and reopen tab , then and only then will the change in files be detected by the service worker and then we can give users the toast to reload for fresher content.

**Comment by jeffposnick** [comment]
`sw-precache` detects that there's new content when the service worker JavaScript is fetched from the network, and the file's contents are different from the contents of the current service worker. That kicks off the `install` event handler, which in turn caches all the new content.

There's more information about how and when the service worker JavaScript is fetched at http://stackoverflow.com/a/38854905/385997, but in general, it will happen when there's a reload or a navigation to another page under the service worker's scope.
