### ISSUE TITLE
Progressive webapp with shell cached still not behaving as desired?

### ISSUE THREAD

**Issue by jasan-s** [GoogleChrome/sw-precache#176]
I have used Sw-precache in my React app to pre-cache my built assets(i.e vendor.js, app.js and, icons). however, the result is less than desirable.  On page reload my app assets are all fetched again(from service worker), but never the less everything disappears (page goes blank) for a moment and assets appear. 
[Screen capture of my app on page reload][1]. In comparison, here is an app [the Session][2] from a list from https://pwa.rocks/. That truly has a offline cached that even on reload does not re-fetch the static assets. [Here is also a screen capture of the session app on page reload][3]. I'm positive there is something I am Not doing. What am i missing? 

  [1]: https://drive.google.com/open?id=0B5LPkXe_6li5QXlxbjdiS3F1Rms
  [2]: https://thesession.org/
  [3]: https://drive.google.com/open?id=0B5LPkXe_6li5R05ZcVFmRDUxWWM

**Comment by jeffposnick** [comment]
Hello @jasan-s—The way I'd go about diagnosing whether this is something related to `sw-precache` is to check out the Network panel of Chrome's DevTools when you reload your page.

You should, ideally, see all your precached resources show up with entries next to the showing that they originated from the service worker, and they should all have a short response time. If you see one or two outliers in your critical path that should be served from `sw-precache`'s cache but aren't, that would point to, e.g., a misconfiguration of `sw-precache`.

If all of your local resources are being quickly and properly served from `sw-precache`, then that points to an issue with your client-side code itself, not `sw-precache`. I'm afraid that diagnosing what's going on in that case is likely to be outside the scope of the `sw-precache` issue tracker.

**Comment by jasan-s** [comment]
thanks Jeff, I have confirmed that Sw-precache is working beautifully and serving all content cached. (longest time is taken by my vendor.js ~548ms served from SW). it is due to mt client side code.  It may be that the session PWA is using server-side rendering (total newb in isomorphic apps).

**Comment by jasan-s** [comment]
Jeff, if you have a second take a glance over at this screenshot of my network re
![app_network_frames-timeline](https://cloud.githubusercontent.com/assets/13863953/18457212/977b9400-790b-11e6-845b-9f63044366ac.png)
sponse at page reload.

**Comment by jeffposnick** [comment]
I'm not sure that there's anything that can be done on the `sw-precache` front, unless you expected all of the files after the `getAccountInfo` to also be precached (they're not; they're being read from the browser cache, though).

**Comment by jasan-s** [comment]
jeff,  I looked at that timeline profiling, and it seems the browser is evaluating the vendor.js (1.24MB) for my app the longest. And then parsing html and my app.js script. This might be a silly question but is it possible to  use service worker to stop browser from refetching the vendor script or the app script at all if it hasn't changed, since my service worker registration scripts runs before my vendor and app scripts?

**Comment by jeffposnick** [comment]
@jasan-s—It sounds like you're asking whether the service worker could help by caching the evaluated/parsed JavaScript. Unfortunately, that's not possible.

The service worker can only intervene at the network level. Once a resource has been fetched (via the network, HTTP cache, or service worker), it's up to the browser itself to determine how to parse and handle it.

Cutting down on the size of your `vendor.js` bundle by breaking it into smaller pieces that are loaded on demand sounds like the right approach. Unfortunately, that's outside the scope of the `sw-precache` issue tracker.
