### ISSUE TITLE
sw-precache in electron app

### ISSUE THREAD

**Issue by tleunen** [GoogleChrome/sw-precache#177]
I've successfully installed sw-precache in a web application and when checked in Chrome, I can see it working fine. But if the webpage is loaded inside a BrowserWindow in Electron, the service worker doesn't work and all requests are giving a `net::ERR_FAILED`.

Do you know how to resolve this?

```
The FetchEvent for "http://localhost:9090/build.js" resulted in a network error response: an object that was not a Response was passed to respondWith().
```

**Comment by jeffposnick** [comment]
I'm sorry, but I don't have any familiarity with using Electron.

 I see https://github.com/electron/electron/issues/2831 which covers something sort-of-similar, along with what looks to be some workarounds.

If nothing in that thread helps, could you pass along a link to the source code for your app? I'd have to dig in a bit to see what might be going on.

**Comment by tleunen** [comment]
In my case it's a remote URL, not a local one, so I don't think the thread will help me :/

My app is unfortunately private, but I can try to setup another small app to reproduce the issue, with another url which use sw-precache.

**Comment by jeffposnick** [comment]
Sure, that would be appreciated. Thanks!

**Comment by tleunen** [comment]
I tested it with another webiste using sw-precache and it works fine inside electron, so I'm closing the issue.
I'll try to see what could be wrong with my website then.

**Comment by jeffposnick** [comment]
Sure thing. Feel free to re-open if it does turn out to be anything related to `sw-precache`.

**Comment by tleunen** [comment]
Hard to know where the issue really is, because I wasn't able to reproduce this with another app.

But, while debugging the service worker, I can see it tries to fetch `index.html` from the cache, returns the promise with `cache.match(urlsToCacheKeys.get(url))` but it seems it's the only request the service worker is receiving, even if there are scripts/styles in the index page for example.

**Comment by tleunen** [comment]
Also, for a quick 1/2 second, I can see this in the console:
```
The FetchEvent for "https://mypage.com/" resulted in a network error response: an object that was not a Response was passed to respondWith().
```

The first time the page load, everything is fine (because the worker is not installed), but then it seems to fail on some files.
```
The FetchEvent for "https://mypage.com/style.css" resulted in a network error response: an object that was not a Response was passed to respondWith().
The FetchEvent for "https://https://mypage.com/build.min.js" resulted in a network error response: an object that was not a Response was passed to respondWith().
```

**Comment by Fl4v10** [comment]
> Also, for a quick 1/2 second, I can see this in the console:
> 
> ```
> The FetchEvent for "https://mypage.com/" resulted in a network error response: an object that was not a Response was passed to respondWith().
> ```
> The first time the page load, everything is fine (because the worker is not installed), but then it seems to fail on some files.
> 
> ```
> The FetchEvent for "https://mypage.com/style.css" resulted in a network error response: an object that was not a Response was passed to respondWith().
> The FetchEvent for "https://https://mypage.com/build.min.js" resulted in a network error response: an object that was not a Response was passed to respondWith().
> ```
> Note: From localhost, everything looks ok :/

Hello,

Can you share the link to your project that works? My electron app does not even try to download the new app.

Thanks.
