### ISSUE TITLE
It is not possible to add custom codes to service-worker

### ISSUE THREAD

**Issue by wilbyang** [GoogleChrome/sw-precache#183]
It is not possible to add custom codes to service-worker if we use the auto-generation for service worker

**Comment by jeffposnick** [comment]
The [`importScripts`](https://github.com/GoogleChrome/sw-precache#importscripts-arraystring) option allows you to write your own custom service worker logic in standalone JavaScript files, and import them into the `ServiceWorkerGlobalScope`.
