### ISSUE TITLE
app-shell-demo does not work

### ISSUE THREAD

**Issue by ChrisCinelli** [GoogleChrome/sw-precache#194]
I tried a bunch of things (all `step*` branches, `npm install`,  etc).

I am getting:
```
✘-1 ~/others/sw-precache/app-shell-demo [step4|✔]
14:51 $ gulp build:dist
[14:52:07] Working directory changed to ~/others/sw-precache
[14:52:07] Using gulpfile ~/others/sw-precache/gulpfile.js
[14:52:07] Task 'build:dist' is not in your gulpfile
[14:52:07] Please check the documentation for proper gulpfile formatting
```

**Comment by jeffposnick** [comment]
Sorry about that—I attempted to fix it in https://github.com/GoogleChrome/sw-precache/pull/190, which is a change that had to be reverted due to an incompatability with Windows, and I'll come up with a better solution.

Doing an `npm install` in the top-level `sw-precache` directory before doing the `npm install` in the `app-shell-demo` directory seems to be a workaround.

**Comment by ChrisCinelli** [comment]
I did that. But it still does not work.

**Comment by jeffposnick** [comment]
Sorry; you can just run an explicit `gulp build:dist` from inside the `app-shell-demo` directory and it will accomplish the same thing.

I'm going to remove the `gulp build:dist` from the `postinstall` script, as it's only really needed when I deploy to https://ifixit-pwa.appspot.com/, so it's not generally useful.

I want to hold off on touching this code for a few more days, as it's being used in its current incarnation as part of the https://events.withgoogle.com/pwa-roadshow-north-america/ events, and the presenters are familiar with the current workarounds. I'll leave this open and address it in a few days.

**Comment by ChrisCinelli** [comment]
You could use a new branch, maybe. 
I did run `gulp build:dist` from inside the `app-shell-demo`. But this is the result:
```
✘-1 ~/others/sw-precache/app-shell-demo [step4|✔]
14:56 $ gulp build:dist
[12:25:42] Working directory changed to ~/others/sw-precache
[12:25:42] Using gulpfile ~/others/sw-precache/gulpfile.js
[12:25:42] Task 'build:dist' is not in your gulpfile
[12:25:42] Please check the documentation for proper gulpfile formatting
```
