### ISSUE TITLE
Using geolocation WatchPosition keeps adding to site storage

### ISSUE THREAD

**Issue by jasan-s** [GoogleChrome/sw-precache#205]
I'm using navigator.geolocation.watchPosition function to get up-to-date user location. However, I'm noticing that on Mobile Chrome the site usage storage data keep increasing until I assume it hit a threshold and clears the geo data and starts adding to the storage again. Is this normal expected behavior of using Geolocation? Or is this a side-effect of sw-precache?

update: This is not the normal expected behavior from watchLocation.

**Comment by jeffposnick** [comment]
`sw-precache` and `sw-toolbox` (via `runtimeCaching`) only cache HTTPS requests. If you're using a browser-provided API that returns data, and there's no HTTPS request being made to obtain that data, then `sw-precache` will never even get a chance to interact with that.
