### ISSUE TITLE
Broken image "Dependency Status"

### ISSUE THREAD

**Issue by tobireif** [GoogleChrome/sw-precache#223]
![screenshot](https://cloud.githubusercontent.com/assets/80411/20960827/8c139f46-bc62-11e6-82e4-6956f99be4ee.png)

**Comment by jeffposnick** [comment]
I think the underlying service was unhappy for a bit. It's back now:
<img width="404" alt="screen shot 2016-12-07 at 2 15 16 pm" src="https://cloud.githubusercontent.com/assets/1749548/20982707/ab587c4e-bc87-11e6-830d-823659402cea.png">
