### ISSUE TITLE
Trouble with SW updates

### ISSUE THREAD

**Issue by HenrikJoreteg** [GoogleChrome/sw-precache#224]
Hi, first off thanks for sw-precache!  Would much appreciate some help sorting out a confusing issue. If i should ask this elsewhere, please let me know.

I'm using sw-precache and it working well *except for the update flow when we deploy a new version*. 

Here's what seems to happen:

1. The browser recognizes there’s a new SW, it gets installed/activated
2. We prompt the user that a new version of the app is available
3. Tapping said prompt refreshes the browser, because at this point supposedly new stuff is cached.
4. But… instead of showing new cached page, it keeps serving the *old* html page from the service worker and now the assets its referring to have been deleted.

Why is it serving the old `/` page from the service worker after supposedly precaching the new stuff?

So the end result is you end up in a scenario where CMD+R is broken because the SW loads the old html that references assets that now no longer exist on the server but if you CMD+Shift+R it loads fine, but even after the "new" service worker is registered it still fails if you CMD+R.

Here's a gist with the relevant pieces of the app SW registration and the generated SW.js, as well as the config used to generate it: https://gist.github.com/HenrikJoreteg/179f230bb89a7442274482168f476211

The other relevant thing to know is that we have nginx configured to serve `/index.html` as `/` and that should be the fallback for all non-asset urls, such as `/some/example`

Any guidance would be much appreciated. Thanks!

**Comment by jeffposnick** [comment]
Sorry to hear that you're running into issues, @HenrikJoreteg. I may need to dig a little deeper, but there is one quick thing to check first—I see that you're using `dontCacheBustUrlsMatching: /./` in your configuration. Are you explicitly using HTTP cache directives to prevent `/` from being stored in the browser cache, by, e.g., setting `max-age: 0`?

If you're *not* taking those steps, then `dontCacheBustUrlsMatching: /./` could be dangerous, because the request for the updated `/` may end up being fulfilled from the browser cache, rather than from the network.

**Comment by HenrikJoreteg** [comment]
@jeffposnick thanks for the quick response, that sounds like a likely culprit. I'll report back.

**Comment by jeffposnick** [comment]
Cool. `dontCacheBustUrlsMatching` can come in handy when you're really confident that your HTTP caching is configured ideally (i.e.: zero caching for navigation target URLs, long-lived caching for subresources that include fingerprinting somewhere in their URLs), but can lead to unfortunate situations otherwise.

**Comment by HenrikJoreteg** [comment]
@jeffposnick that seems to have resolved the issue, just to summarize what the problem/solution was for anyone else who stumbles across this:

**What was happening:** 

SW was updating, it was pre-fetching new assets which resulted in a GET on the root HTML document, in our case `/`. However, this HTTP request was being answered from cache and thereby referencing `.js` and `.css` files that no longer existed in the server *and* had been wiped from the SW cache as well by the update process. As a result, when refreshing the page, the SW would answer with its cached copy of the document, but not have any of the supporting resources (since their URLs had changed when we built).

**The fix**

HTML requests for things like `/dashboard`, `/account`, and `/` were incorrectly reloaded from the browser cache because those names never changed. 

We could've fixed this by modifying cache headers in our file server so explicitly tell the browser to never cache HTML resources. But in our case, it was easier (and felt more future proof against future file server changes) to change the sw-precache config to only cache bust URLs that didn't have file extensions. We did that by setting the `dontCacheBustUrlsMatching:` option to: `/^(?=.*\.\w{1,7}$)/` which basically says "has a file extension".

Hope that helps someone. 

Thanks again @jeffposnick!

**Comment by jeffposnick** [comment]
Yup! That danger is why we `sw-precache` cache-busts everything by default, and requires that folks opt-out of it using `dontCacheBustUrlsMatching` if they feel confident that they need to.

This is something that much of the sample code out there for service worker precaching doesn't address; it's easy to get burned by the HTTP cache in this scenario!
