### ISSUE TITLE
How to implement "cache first then network" and "network first then cache" strategies

### ISSUE THREAD

**Issue by mlcdf** [GoogleChrome/sw-precache#235]
Hi

Using `sw-precache` & `sw-toolbox, is there a way to implement "cache first then network" and "network first then cache" strategies (for different assets) ?

The problem is that if I add a file to `staticFileGlobs`, in addition of being cached when the service worker is installed (which is what I want), the file is also always served from this cache, even when using the handler `networkFirst`.

**Comment by jeffposnick** [comment]
Files that `sw-precache` manages, i.e. those that are matched by the `staticFileGlobs`, are always served cache-first, and updates happen only as a result of re-running `sw-precache` and deploying a fresh build.

If you have a set of resources that need a different response strategy, then make sure that they *aren't* matched by any of the `staticFileGlobs` patterns, and use the [`runtimeCaching` option](https://github.com/GoogleChrome/sw-precache#runtime-caching) to set up an appropriate URL pattern and strategy (`networkFirst`, etc.) to match those requests.

**Comment by mlcdf** [comment]
I'll look into that. Thanks!

**Comment by m-mansoor-ali** [comment]
@mlcdf did you find a way to do it ? 
I want to serve cached resources and then do an update for those resources in background so that the next request will serve the updated data.
Something like this : [(https://serviceworke.rs/strategy-cache-and-update.html)]
but using sw-precache

**Comment by mlcdf** [comment]
Hello @m-mansoor-ali 
I can't remember if I managed to make it worked as I wanted. Sorry.

**Comment by m-mansoor-ali** [comment]
@jeffposnick please update
