### ISSUE TITLE
sw-precache doesn't add service-worker-registration.js

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [GoogleChrome/sw-precache#237]
Currently, `sw-precache` doesn't add `service-worker-registration.js` file to project. Users need download https://github.com/googlechrome/sw-precache/blob/master/demo/app/js/service-worker-registration.js and add it manually every time.

**Comment by jeffposnick** [comment]
Right, that's expected. That `service-worker-registration.js` file is isn't meant to be automatically injected into your codebase. You could adapt it and incorporate it as you see fit, but it's up to you to decide which pages should trigger SW registration, where you serve you `service-worker.js` file from, whether you want to take addition post-registration steps like ask for push notification permissions, etc.

There isn't a one-size-fits-all solution.
