### ISSUE TITLE
The cached response that was expected is missing?

### ISSUE THREAD

**Issue by ghatul** [GoogleChrome/sw-precache#238]
All content which is listed in serviceworker.js not going to store in browser cache 

Couldn't serve response for "http://localhost:5555/assets/logo/logo-color.png" from cache: Error: The cached response that was expected is missing.
    at Error (native)
    at http://localhost:5555/service-worker.js:217:19message: "The cached response that was expected is missing."stack: (...)get stack: get stack()set stack: set stack()__proto__: Object

**Comment by jeffposnick** [comment]
Have you manually manipulated the cache or cleared entries using the browser's DevTools?

If you "start fresh" inside a Chrome Incognito window and then visit your site, does the issue persist?

**Comment by ghatul** [comment]
yes i cleared cache also check in Incognito mode but it not worked and service_worker not registered in Incognito mode

**Comment by jeffposnick** [comment]
Service workers do register in Chrome's Incognito mode. They're automatically de-registered and caches are cleared once you close the last Incognito window.

If you manually cleared the cache prior to seeing the error message you reported, then that's the explanation. `sw-precache` expected to find a cached entry, but it's not there (because it was manually cleared). `sw-precache` won't automatically repopulate the cache, but it will just fall back to using a response from the network (assuming you're online), which is about the best you could safely do.

**Comment by shrisggs** [comment]
ok first thing is that i didnt clear cache manually,  my main problem is that resources/files are not caching in browser cache on production build it may be path issue but  i  dont  understand it. 
Let i  will explain inn  following steps what  is going on,

1. i  add gulp task for create service worker
2. i add that task in run-sequence  which crate production build 
3. serivce-worker.js is successfully created 
5. I  also check  service-worker.js file code which create precaheconfig list which contain alll fille paths   which i want to stored in cache but not stored in browser cache
6. http:localhost:8080//i hit this in browser. show message in console service worker get registered but
     here no one resource/file going stored in browser cache
7. If I going to access  http:localhost:8080/service-worker.js in browser but i cant access it and it redirect to my default url.
8. and also service-worker.js not registered other than 8080 port i dont understand why
9. I also check with https: but same thing happen
10. In development build all files are cached and also i can access http:localhost:8080/service-worker.js through browser url.

below Steps i performed using gulp for configuration of service-worker:-

1. gulp.task('build.prod', (done: any) =>
runSequence('check.tools',
'clean.prod',
//'tslint',
//'css-lint',
'build.assets.prod',
'build.html_css',
'copy.prod',
'copy.server.js.prod',
'build.server.prod',
'build.js.prod',
'build.bundles',
'build.bundles.app',
'minify.bundles',
'build.index.prod',
'copy.server.assets',
'generate-service-worker',
done));

2. gulp.task('generate-service-worker', (callback:any) => {
var path = require('path');
var swPrecache = require('sw-precache');
var rootDir = 'dist/prod/client/';
//var rootDir = Config.APP_CLIENT_DEST;
util.log('---------------------generate-service-worker-----------root-directoryName---',rootDir);
swPrecache.write(${rootDir}/service-worker.js, {
staticFileGlobs: [rootDir + '/**/*.{js,html,css,png,jpg,gif,svg,eot,ttf,woff,json}'],
stripPrefix: rootDir
}, callback);
});

3. index.html
<% if (BUILD_TYPE === 'prod') { %>
<script>
  if('serviceWorker' in navigator) {
    console.log('Service Worker started.');
    navigator.serviceWorker.
    register('./service-worker.js')
      .then(function(serviceWorker) {
        console.log("Service Worker Registered");
      });
  }
</script>
<% } %>

4. ScreenShot of dist folder

![tplscreeenshot](https://cloud.githubusercontent.com/assets/10724762/22919476/204ff428-f2b6-11e6-90af-c47560551de8.png)


5. i use this project as starter - [https://github.com/vyakymenko/angular2-seed-express](url)

**Comment by ghatul** [comment]
ok first thing is that i didnt clear cache manually,  my main problem is that resources/files are not caching in browser cache on production build it may be path issue but  i  dont  understand it. 
Let i  will explain inn  following steps what  is going on,

1. i  add gulp task for create service worker
2. i add that task in run-sequence  which crate production build 
3. serivce-worker.js is successfully created 
5. I  also check  service-worker.js file code which create precaheconfig list which contain alll fille paths   which i want to stored in cache but not stored in browser cache
6. http:localhost:8080//i hit this in browser. show message in console service worker get registered but
     here no one resource/file going stored in browser cache
7. If I going to access  http:localhost:8080/service-worker.js in browser but i cant access it and it redirect to my default url.
8. and also service-worker.js not registered other than 8080 port i dont understand why
9. I also check with https: but same thing happen
10. In development build all files are cached and also i can access http:localhost:8080/service-worker.js through browser url.

below Steps i performed using gulp for configuration of service-worker:-

1. gulp.task('build.prod', (done: any) =>
runSequence('check.tools',
'clean.prod',
//'tslint',
//'css-lint',
'build.assets.prod',
'build.html_css',
'copy.prod',
'copy.server.js.prod',
'build.server.prod',
'build.js.prod',
'build.bundles',
'build.bundles.app',
'minify.bundles',
'build.index.prod',
'copy.server.assets',
'generate-service-worker',
done));

2. gulp.task('generate-service-worker', (callback:any) => {
var path = require('path');
var swPrecache = require('sw-precache');
var rootDir = 'dist/prod/client/';
//var rootDir = Config.APP_CLIENT_DEST;
util.log('---------------------generate-service-worker-----------root-directoryName---',rootDir);
swPrecache.write(${rootDir}/service-worker.js, {
staticFileGlobs: [rootDir + '/**/*.{js,html,css,png,jpg,gif,svg,eot,ttf,woff,json}'],
stripPrefix: rootDir
}, callback);
});

3. index.html
<% if (BUILD_TYPE === 'prod') { %>
<script>
  if('serviceWorker' in navigator) {
    console.log('Service Worker started.');
    navigator.serviceWorker.
    register('./service-worker.js')
      .then(function(serviceWorker) {
        console.log("Service Worker Registered");
      });
  }
</script>
<% } %>

4. ScreenShot of dist folder

![tplscreeenshot](https://cloud.githubusercontent.com/assets/10724762/22919476/204ff428-f2b6-11e6-90af-c47560551de8.png)


5. i use this project as starter - [https://github.com/vyakymenko/angular2-seed-express](url)

**Comment by jeffposnick** [comment]
Can you point me to either a public deployment of your site, or a GitHub repo that contains your actual code that I could then build and deploy myself?

**Comment by ghatul** [comment]
hi, very sorry , i dont have permission to do that ,

i solved cache issue now my all resources are stored successfully in cache and service-worker registered, install and start without error.
(that issue was directory permission access)

but now issue with fetch event, when i choose offline mode through dev-tools and hit url then it not works
in offline. I checked network call status in offline max resources accessed through  service-worker from cache and on screen shows my first flashscreen  image thats it



![1111](https://cloud.githubusercontent.com/assets/19589441/22964546/3fff77b6-f37f-11e6-8114-d0c8063d9488.png)

**Comment by jeffposnick** [comment]
There are a number of failures related to URLs that have timestamp query parameters appended to the end of them (like main.css?148...). Those URLs aren't going to appear in the `sw-precache`-managed caches.

If you need to request those URLs with query parameters, and you want them to match against the versions that are cached which don't contain the query parameters, then you could configure the [`ignoreUrlParametersMatching`](https://github.com/GoogleChrome/sw-precache#ignoreurlparametersmatching-arrayregex) option with the value `[/./]`.

**Comment by Janie-w3** [comment]
Hi @ghatul ,
Could you please inform me which directory needs to have enough permission? it that only read (4) permission?

**Comment by ghatul** [comment]
Hi @Janie-w3 ,

I used client-server seed, which I mentioned above.
      app.use(express.static(root));
      app.use(express.static(clientRoot))

express.static is used to serve files(images, js files, css etc). I used this code to get permissions (to allow access).
