### ISSUE TITLE
Question: sw-precache vs sw-helpers/sw-precaching

### ISSUE THREAD

**Issue by norbert989** [GoogleChrome/sw-precache#247]
Hello, is the a practical difference between sw-precache and sw-precaching, where sw-precaching sits in the sw-helpers libraries section?

Is there any relation between them or are they going in their own separate ways?

Thanks in advance.

**Comment by jeffposnick** [comment]
The difference between `sw-precache` and `sw-toolbox` is explained in this document: https://github.com/GoogleChrome/sw-precache/blob/master/sw-precache-and-sw-toolbox.md

[`sw-helpers`](https://github.com/GoogleChrome/sw-helpers/) is a collection of smaller modules that amounts to a refactoring/modernization of both `sw-precache` and `sw-toolbox`. One of the goals is to make a single, unified interface for both buildtime and runtime caching (which we're currently developing as [`sw-lib`](https://github.com/GoogleChrome/sw-helpers/tree/master/packages/sw-lib)). We hope that having that single interface will lead to less confusion vs. having two completely different libraries nowadays.

The fact that we're building on top of smaller modules this time around also means that other service worker implementations can borrow functionality, i.e. just use the cache expiration code without having to use the entirety of the framework.

Both `sw-precache` and `sw-toolbox` remain supported (and I'm about to cut a major 5.0.0 release of `sw-precache`). Once `sw-lib` is ready, we expect a smooth migration path that will allow the new code to read in existing `sw-precache` configuration and generate an equivalent service worker.
