### ISSUE TITLE
POST with CORS not work?

### ISSUE THREAD

**Issue by elvizlai** [GoogleChrome/sw-precache#248]
I use webpack to build.

```
    new SWPrecacheWebpackPlugin({
      cacheId: 'v3',
      filename: 'sw.js',
      maximumFileSizeToCacheInBytes: 4194304,
      minify: true,
      staticFileGlobs: [
        'dist/**.html',
        'dist/static/**.*',
        'dist/static/fonts/**.*',
        'dist/static/css/**.css',
        'dist/static/img/**.*',
        'dist/static/js/**.js'
      ],
      staticFileGlobsIgnorePatterns: [/\.map$/],
      stripPrefix: 'dist',
      mergeStaticsConfig: true,
      runtimeCaching: [{
        handler: 'networkFirst',
        urlPattern: /^(https:\/\/)[^\s]+\/detail\/\w*-\w*-\w*-\w*-\w*/,
        method: 'post',
      }],
    })
```

The urlPattern that match has CORS. 

 I saw the generated sw.js. It looks fine in the finall:

```
toolbox.router.post(/^(https:\/\/)[^\s]+\/detail\/\w*-\w*-\w*-\w*-\w*/,toolbox.networkFirst,{});
```

but It looks like the fetch only works with GET method:

```
self.addEventListener('fetch', function(event) {
  if (event.request.method === 'GET') {
      ......
```

Did I missing something?

**Comment by barinali** [comment]
Afaik there is no support for POST method on Service Worker. There is a [stackoverflow answer](http://stackoverflow.com/a/35272243/2324048) with some links. I hope it helps.

**Comment by jeffposnick** [comment]
Basically what @barinali said. While it's possible to intercept `POST` requests, you can't directly store them using the Cache Storage API, so you'd need to write custom code to do something specific (like serialize the bodies in IndexedDB) other than store them in the cache.
