### ISSUE TITLE
Progressive web app offline refresh doesn't work

### ISSUE THREAD

**Issue by pmrotule** [GoogleChrome/sw-precache#252]
I recently made my first progressive web app with a service worker generated by _sw-precache_. I've run the default Gulp task in the demo. I deployed what was generated in the _dist_ folder and I added a manifest file to make it a pwa:

```
{
  "short_name": "On Peak",
  "name": "On Peak long name",
  "description": "Description of On Peak.",
  "icons": [
    {
      "src": "images/icons/pwa-logo_48.png",
      "type": "image/png",
      "sizes": "48x48"
    },
    {
      "src": "images/icons/pwa-logo_96.png",
      "type": "image/png",
      "sizes": "96x96"
    },
    {
      "src": "images/icons/pwa-logo_192.png",
      "type": "image/png",
      "sizes": "192x192"
    }
  ],
  "start_url": "index.html?launcher=true",
  "display": "fullscreen",
  "orientation": "landscape",
  "theme_color": "#333",
  "background_color": "#333"
}
```

Everything works fine and I am able to navigate through the web app when I am offline using Chrome on mobile or using the icon created by Chrome using the _Add to home screen_ option (my progressive web app). If that matters, I've used the option in the menu of the browser without visiting the website twice to see the app install banner.

I only have one issue: if I am offline and I refresh the page in Chrome, it still works but if I do the same using the pwa, it shows the dinosaur and the _You are offline_ message (refresh by scrolling up). If I navigate through the app without refreshing a page, no dinosaur.

Here is the app using your demo: [https://karmapla.net/](https://karmapla.net/)

**Comment by jeffposnick** [comment]
Your `start_url` is 'index.html?launcher=true'. That means that when you refresh your added-to-homescreen version of your web app, that specific URL is going to be used to match against the cache. You don't have a version of 'index.html' stored in your cache that includes the '?launcher=true' query string, so the cache match will fail.

You can work around this by telling `sw-precache` which URL query parameters to ignore when performing cache matches, via the [`ignoreUrlParametersMatching` option](https://github.com/GoogleChrome/sw-precache#ignoreurlparametersmatching-arrayregex). By default, it's set to `[/^utm_/]`, so if you had used, e.g., '?utm_source=launcher' as the query parameter, things would have Just Worked. But if you want to keep '?launcher=true', then just set `ignoreUrlParametersMatching: [/^launcher/]` in your `sw-precache` configuration.
