### ISSUE TITLE
Cannot get app shell work

### ISSUE THREAD

**Issue by dingcaiying** [GoogleChrome/sw-precache#255]
I'm not sure if I mistake something. How I start the app-shell-demo is:  inside `/app-shell-demo` folder, do `npm install` `npm start`. But I got this error:
```Error: Cannot find module '../build/rev-manifest.json'```.

Did I miss any step to start?

**Comment by dingcaiying** [comment]
And I'm on master branch.

**Comment by jeffposnick** [comment]
Sorry, it's setup using `gulp` rather than npm scripts for local development/testing.

After installing `gulp` globally, you can try things out with `gulp build:dist && gulp serve`.
