### ISSUE TITLE
Integration with sw-offline-google-analytics

### ISSUE THREAD

**Issue by ciampo** [GoogleChrome/sw-precache#256]
Hello,
is there a built-in way to integrate the sw-precache library to generate a SW that uses sw-offline-google-analytics ?
I guess the only alternative would be to provide a custom template.

Thanks

**Comment by jeffposnick** [comment]
Yup—you can pull in additional code into the service worker that `sw-precache` generates by configuring the [`importScripts` option](https://github.com/GoogleChrome/sw-precache#importscripts-arraystring). Just pass in the path to any JavaScript file and it will be automatically included in your service worker, using the [`importScripts()` API call](https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/importScripts) under the hood.

**Comment by caleb531** [comment]
@jeffposnick just saw this, however according to the [Offline Google Analytics docs](https://developers.google.com/web/updates/2016/07/offline-google-analytics), `goog.offlineGoogleAnalytics.initialize();` must be called after `importScripts` for things to work. How can *this* initialization be done with `sw-precache`?

Thanks,
Caleb

**Comment by niiapa** [comment]
Anyone know a valid response to this? I've searched for a couple of days but nothing.

**Comment by jeffposnick** [comment]
You could accomplish that via

Inside `offline-analytics-init.js`:

```js
goog.offlineGoogleAnalytics.initialize();
```

`sw-precache` config:

```js
{
  importScripts: ['path/to/offline-google-analytics-import.js', 'offline-analytics-init.js'],
  // ..other options...
}
```

If the `path/to/offline-google-analytics-import.js` entry is listed first in that array, then it will execute first, and `goog.offlineGoogleAnalytics` will be defined in the global scope by the time `offline-analytics-init.js` executes.
