### ISSUE TITLE
Update existing service worker instead of generating a new one

### ISSUE THREAD

**Issue by alcfeoh** [GoogleChrome/sw-precache#257]
`sw-precache` can `generate ` or `write ` a service worker, but what about `update`? My project already has a service worker in place and I would like to use sw-precache to update the file names that are generated by my Angular CLI build (minified and appended into files for which I don't know the name upfront).

Is there any way I could tell `sw-precache` "Here is my service worker file, just update the cached files names and that's it"?

**Comment by jeffposnick** [comment]
There isn't. `sw-precache` doesn't have a mode that will just swap out file names.

If all you're looking to do is that, then using a build-time tool that generates a manifest and then uses that manifest to do replacements is probably your best bet. I have, for instance, used [`gulp-rev`](https://github.com/sindresorhus/gulp-rev) as part of a `gulp` build process in the past.

`sw-precache` assumes that it generates the top-level service worker, and will automatically handle the caching, update, and serving strategy for all the files it manages.

**Comment by alcfeoh** [comment]
Sounds good, will be looking for such a tool for Webpack / Angular CLI then.
