### ISSUE TITLE
Navigation Preload in sw-precache

### ISSUE THREAD

**Issue by mukilane** [GoogleChrome/sw-precache#259]
Can the new experimental feature "Navigation Preload" be integrated to sw-precache?
Refer: https://developers.google.com/web/updates/2017/02/navigation-preload

**Comment by jeffposnick** [comment]
This snippet from the article is relevant:

> The boot-up time isn't a problem if you're responding from the cache, as the benefit of skipping the network is greater than the boot-up delay. But if you're responding using the network…

If you're using `sw-precache` effectively, you should be responding to navigations from the cache. (Either serving page-specific HTML, or serving an App Shell via configuring [`navigateFallback`](https://github.com/GoogleChrome/sw-precache#navigatefallback-string).)

So I don't think it makes sense to add in Navigation Preload support to `sw-precache`.

If you do have a scenario in which you **need** to add in support, you can do so by writing an additional `fetch` handler in a standalone JavaScript file, and then pulling that into your service worker via the [`importScripts`](https://github.com/GoogleChrome/sw-precache#importscripts-arraystring) configuration option.
