### ISSUE TITLE
Question: Should I include the raw or gzipped version of files?

### ISSUE THREAD

**Issue by Secretmapper** [GoogleChrome/sw-precache#264]
This may seem like a dumb question, but I couldn't find any conclusive answers googling. If I'm compressing my assets, should I include the raw assets or gzipped assets?

I'm using the `SWPrecacheWebpackPlugin`, and I'm currently ignoring gzipped files. This makes my TotalPrecacheSize balloon in size.

```
    new SWPrecacheWebpackPlugin({
      cacheId: '',
      filename: '',
      maximumFileSizeToCacheInBytes: 4194304,
      navigateFallback: '/assets/index.html',
      staticFileGlobsIgnorePatterns: [
        /\.ejs$/,
        /\.gz$/
      ]
    })
```

Should I ignore the raw files and be including the gzipped files instead?

**Comment by jeffposnick** [comment]
Thanks for the question!

So, if you're actually fetching `.gz` files (and then, like, uncompressing them at runtime via JavaScript?) then it might be appropriate to have them precached.

If you could provide a bit more context about how the assets are being used by your web app—such as the JavaScript that you're using to load the assets, or the DOM elements that reference them—I might be able to provide a more definitive answer.

**Comment by kakadiadarpan** [comment]
I'm pre-caching gzipped JavaScript files. Now when I try to load the application second time, it serves the files from cache. But the JS files which are gzipped, do not have this header set 

> "content-encoding:gzip"

Any pointers on how to fix this?

**Comment by jeffposnick** [comment]
I think you're running into what's described by step 12 of https://fetch.spec.whatwg.org/#http-network-fetch

I don't think it's something that `sw-precache` can control directly.
