### ISSUE TITLE
Ability to pass custom variables/options to custom template

### ISSUE THREAD

**Issue by harikrishnakanchi** [GoogleChrome/sw-precache#266]
sw-precache gives an option to generate a serviceWorker from a custom template.  But, there is no ability to pass custom options for modified custom template. It would be more useful if there is an option to pass custom options as shown below.

```
customOptions: {
    "optionA" : "value"
}
```

**Comment by jeffposnick** [comment]
I'd recommend using [`importScripts`](https://github.com/GoogleChrome/sw-precache#importscripts-arraystring) to pull in additional service worker code if the default template doesn't enable all of your use cases.

It's also possible to make your own copy of the template, modify it, and then pass it in via [`templateFilePath`](https://github.com/GoogleChrome/sw-precache#templatefilepath-string), but you risk things going wrong if your template gets out of sync with what `sw-precache` expects following a new release of `sw-precache`.

**Comment by harikrishnakanchi** [comment]
@jeffposnick `importScripts` option doesn't fit if there is some changes needed in existing event handlers present in default `serviceWorker` template. The intention behind introducing custom options is to minimize changes in original `sw-precache` template. People can easily add their custom code without many changes and makes easy for them to be up to date with original `sw-precache` template. (Like the way we pass `externalFunctions` to template in source code).

**Comment by jeffposnick** [comment]
If there's some additional behavior that you'd like the templated service worker to perform, then I'd be interested to hear what it is, and if it sounds generally useful, either include it by default or create a configuration option that configured that new specific functionality.
