### ISSUE TITLE
`.write()` convenience function

### ISSUE THREAD

**Issue by sindresorhus** [GoogleChrome/sw-precache#27]
The use of this module in WSK is currently a bit [verbose](https://github.com/google/web-starter-kit/blob/7ab4b8b39592b825bc2b24f920e27447cce990f9/gulpfile.js#L218-L254). Would be nice to be able to simplify it a bit. First I think this module should have a convenience method to write the file to disk.

From:

```js
var rootDir = 'dist';

swPrecache({
  cacheId: packageJson.name || 'web-starter-kit',
  dynamicUrlToDependencies: {
    './': [path.join(rootDir, 'index.html')]
  },
  staticFileGlobs: [
    rootDir + '/fonts/**/*.woff',
    rootDir + '/images/**/*',
    rootDir + '/scripts/**/*.js',
    rootDir + '/styles/**/*.css',
    rootDir + '/*.{html,json}'
  ],
  stripPrefix: path.join(rootDir, path.sep)
}, function (error, serviceWorkerFileContents) {
  if (error) {
    return callback(error);
  }
  fs.writeFile(path.join(rootDir, 'service-worker.js'),
    serviceWorkerFileContents, function (error) {
    if (error) {
      return callback(error);
    }
    callback();
  });
});
```

To:

```js
var rootDir = 'dist';

swPrecache.write('service-worker.js', {
  rootDir: 'dist',
  cacheId: packageJson.name || 'web-starter-kit',
  dynamicUrlToDependencies: {
    './': [path.join(rootDir, 'index.html')]
  },
  staticFileGlobs: [
    rootDir + '/fonts/**/*.woff',
    rootDir + '/images/**/*',
    rootDir + '/scripts/**/*.js',
    rootDir + '/styles/**/*.css',
    rootDir + '/*.{html,json}'
  ],
  stripPrefix: path.join(rootDir, path.sep)
}, function () {});
```

And since we specify a `rootDir` option, we might be able to get rid of the `stripPrefix` option usage and the `rootDir` thing in `staticFileGlobs`.

**Comment by sindresorhus** [comment]
@addyosmani

**Comment by jeffposnick** [comment]
Creating a `write()` helper makes sense.

I have a feeling that keeping the various directory-related options inside the core module will be necessary, to accommodate various serving setups, but I'll also think about whether a common setup can be abstracted into an additional parameter or sensible defaults.

**Comment by addyosmani** [comment]
:+1:

**Comment by sindresorhus** [comment]
:+1:
