### ISSUE TITLE
Updating files that are cached at runtime

### ISSUE THREAD

**Issue by lukasoppermann** [GoogleChrome/sw-precache#270]
Hey,

when I update e.g. a subpage and the html is cached at runtime, the service-worker does not refresh. Am I doing something wrong? Does the service-worker only update when a prefetch value changes and not when I run the sw-precache function in my build script?

I am using gulp to run the sw-precache function, if that is important. Please let me know what more info I can provide.

**Comment by jeffposnick** [comment]
It's important that each time you change any of the assets that `sw-precache` manages you re-run the script to generate `sw.js`, and that you always deploy that updated `sw.js` to your production web server alongside the changed assets.

The expected flow is:

1. You use `sw-precache` to generate and deploy a `sw.js`, including precaching info for `subpage.html` (we'll call it version v1).
2. A user visits your site for the first time, `sw.js` is registered, and `subpage.html` v1 is precached.
3. At some point later, you change `subpage.html` to v2, re-run `sw-precache` to generate an updated `sw.js`, and deploy that.
4. At some point later, your user revisits your site. The resources that are loaded initially during this visit come directly from the cache tha `sw-precache` manages.
5. "In the background", your user's browser [automatically refetches](http://stackoverflow.com/questions/38843970/service-worker-javascript-update-frequency-every-24-hours/38854905#38854905) `sw.js` to see if there are any changes. There are changes in this case, and the service worker will take care of downloading `subpage.html` v2 and updating its caches with the latests updates.
6. You can optionally detect that this update occurred and display a message letting the user know that something was updated and that they might want to refresh ([here's an example](https://github.com/GoogleChrome/sw-precache/blob/master/demo/app/js/service-worker-registration.js)). You could alternatively do nothing, and the next time the user visits your site, they'll get the updated assets automatically. The right thing to do might also depend on whether your user is currently navigated to `index.html` (in which case the update to `subpage.html` isn't really relevant) or navigated to `subpage.html` v1 (in which case the `subpage.html` v2 update is relevant).
