### ISSUE TITLE
importScripts is not defined

### ISSUE THREAD

**Issue by denar90** [GoogleChrome/sw-precache#275]
I faced this issue using `importScripts` option.
I want to add additional logic to generated service worker. 

So I have a simple script for additional handling `fetch` event:
```js
self.addEventListener('fetch', function(event) {
  console.log(`One more handler for fetching url: ${event.request.url}`);
});
```

`sw-precache-config.js`
```js
module.exports = {
  staticFileGlobs: [
    'docs/**.css',
    'docs/**.html',
    'docs/Images/**.*',
    'docs/**.js',
    'docs/**.js'
  ],
  runtimeCaching: [{
    // exclude googleapis, analitics, drive requests
    urlPattern: /^((?!(googleapis|analytics|googleusercontent)).)*$/,
    handler: 'networkFirst'
  }],
  importScripts: ['test-worker.js'],
  stripPrefix: 'docs/',
  verbose: true
};

```
Env:
- `sw-precache` v5.0.0
- sw generated using `sw-precache --config=./sw-precache-config.js --root=docs` command

Thanks :)

**Comment by jeffposnick** [comment]
That should be a supported use case, and I tried something similar just now and the generated service worker file seemed to be okay.

Where exactly are you seeing the "importScripts is not defined" error message reported? Are you seeing it when running the command-line tool to generate the service worker file, or are you seeing it logged in the JS Console when your web app attempts to register and use the service worker file?

**Comment by denar90** [comment]
@jeffposnick thanks for reply. Yes, file generated correctly, but after sw registration in browser I'm getting this error in console. It's really strange because `importScripts` part of web workers specification...
In addition sw generated without `importScripts` works totally fine.

---
>That should be a supported use case, and I tried something similar just now and the generated service worker file seemed to be okay.

Have you tried it running in browser? Does it work correctly?

**Comment by jeffposnick** [comment]
Yes, it works fine in Chrome 59, and I'd assume other versions as well:

![screen shot 2017-04-03 at 5 00 19 pm](https://cloud.githubusercontent.com/assets/1749548/24631656/23d90806-188f-11e7-8c2b-ad583fd6fb03.png)

Which browser are you seeing this in? As you say, `importScripts()` is a standard part of the web platform, so it's odd. The only thing that I could think of is that somehow your generated service worker file is being run from the context of the page and not the service worker?

**Comment by denar90** [comment]
@jeffposnick It was just me - dumb thing. sw also became part of the bundle and invoked as usual js file, and missed that 😞 
Thank you for your help and sorry for waisted time.

**Comment by NikRokzz** [comment]
> @jeffposnick It was just me - dumb thing. sw also became part of the bundle and invoked as usual js file, and missed that 😞
> Thank you for your help and sorry for waisted time.

Hi I am facing the same issue. Can you help
