### ISSUE TITLE
Service Worker not re-cacheing changed files. 

### ISSUE THREAD

**Issue by GeorgeChackungal** [GoogleChrome/sw-precache#276]
Hi,

I am using the below gulp task to create the service worker.

```
gulp.task('generate-service-worker', function(callback) {
  var swPrecache = require('sw-precache');
  var rootDir = 'dist/';

  swPrecache.write('dist/service-worker.js', {
    staticFileGlobs: [rootDir + '/**/*.{js,html,css,png,jpg,gif,svg,eot,ttf,woff,woff2,json,ico}'],
    stripPrefix: rootDir,
    maximumFileSizeToCacheInBytes: 10485760
  }, callback);
});
```

The service worker get generated as well as the new dist package. But after making any change to my source & upload the new set of files including the service worker, the files are not getting updated even though the hash is updated for the file I changed.

**Comment by GeorgeChackungal** [comment]
Figured it out. Rookie Mistake. Just added the code from below example

https://github.com/GoogleChrome/sw-precache/blob/master/demo/app/js/service-worker-registration.js

**Comment by isTravis** [comment]
An easy  rookie mistake to make - for those coming from [sw-precache-webpack-plugin](https://github.com/goldhand/sw-precache-webpack-plugin), the readme on that package suggests a quick registration: 

```
(function() {
  if('serviceWorker' in navigator) {
    navigator.serviceWorker.register('/my-service-worker.js');
  }
})();
```

If you skim the README too quickly, you'll miss the link they provide (same link @GeorgeChackungal gives above). 

This short registration code does not have the handlers to deal with updating the service-worker or its cached files.

**Comment by devzsolt** [comment]
@GeorgeChackungal @isTravis I'm using the same logic referred above but when I rebuild my app and reload the page in Chrome then `updatefound` event is never fired until I manually unregister the service worker. I use 
- sw-precache-webpack-plugin 0.9.2
- sw-precache 5.1.1
- Chromium 58.0.3029.81 (64-bit)

What could be wrong in my setup? It's even the same with the original skeleton produced by [preact-cli](https://github.com/developit/preact-cli) and [vue-cli](https://github.com/vuejs/vue-cli)
Dev tools network tab says that service-worker.js comes from disk cache despite app is online, files are available through network, service-worker.js changed and even the Disable cache option in Dev tools is still ticked. Could you please help me?
