### ISSUE TITLE
Files cached but not loaded

### ISSUE THREAD

**Issue by natashache** [GoogleChrome/sw-precache#286]
I'm using sw-precache and its webpack plugin to generate the service worker. And after my app's assets are pre-cached, I also use the [cache api](https://developer.mozilla.org/en-US/docs/Web/API/Cache) to add more files to the cache storage when user clicks on some button. The problem is that when offline, only the pre-cached files are loaded, but not the files added later to the cache storage. 

I thought the fetching for pre-cached files and files cached later shouldn't be different since they are all urls stored in the same storage. 

Would appreciate any insights on why the files cached later are not being retrieved from storage.

**Comment by jeffposnick** [comment]
Hello @natashache—There's two steps needed to ensure that a request for a given URL works while offline. First is making sure that the response for that URL is available via the Cache Storage API, and it sounds like you've done that. The second step is implementing a `fetch` event handler in your service worker that will detect when there's an incoming requests for that URL, and return the response from the cache. This is the part you haven't done.

`sw-precache` automatically sets up a `fetch` event handler that will only respond to requests for URLs that its managing as part of its precache configuration. If you want to respond to additional requests, like requests for URLs not managed by `sw-precache`, then you'll need to implement an additional `fetch` event handler.

You can write this handler yourself, put it in a `custom-handler.js` file, and then include it in your final service worker by using [`importScripts: ['custom-handler.js']`](https://github.com/GoogleChrome/sw-precache#importscripts-arraystring).

Alternatively, if all you want to do is add in some runtime caching logic in addition to the precaching logic, there's a shortcut via the [`runtimeCaching`](https://github.com/GoogleChrome/sw-precache#runtimecaching-arrayobject) configuration option.

**Comment by natashache** [comment]
@jeffposnick Thank you so much for the enlightening response. It's working now.
