### ISSUE TITLE
sw-precache causes strange error messages

### ISSUE THREAD

**Issue by japrescott** [GoogleChrome/sw-precache#287]
I am using sw-precache together with sw-toolbox and everything is working correctly, caching files etc.
The first time I visit, the sw is installed and no errors appear. on a reload in devtools/application I see my sw but it has errors stating "(unkown)#11111: ServiceWorker failed to install"
There is no logs in the console and I don't know where these errors are coming from/originating.

My app uses shebang ( #!/ ) to navigate between states/sites. Could this be an issue?

**Comment by jeffposnick** [comment]
Hello @japrescott—I don't think that the `#!` navigations should be an issue.

Can you pass along a public URL at which I could try out your deployment to troubleshoot further?

**Comment by jeffposnick** [comment]
Please reopen and pass along the additional details if you are still able to reproduce the issue you originally described.
