### ISSUE TITLE
url hashes count as cache misses

### ISSUE THREAD

**Issue by whmountains** [GoogleChrome/sw-precache#290]
Like the title says.  `example.com` works, but `example.com#chapter2` counts as a cache miss and the page fails to load.

Is this a bug, or the intended behavior.  If it's intended, can we add a configuration option to strip hashes?  It could be done inside the `stripIgnoredUrlParameters` function.

**Comment by whmountains** [comment]
Update: I tested in Chrome and it works fine with hashes, so the behavior seems to be Firefox only.

I did some debugging and I think I've found the root of the problem.  `event.request.url` does not include the hash segment in Chrome but in Firefox it does, hence the cache misses.

This may be a bug in Firefox, Chrome, or just an ambiguity in the spec, but in any case it would be an easy fix to work around it in the service worker code.

**Comment by jeffposnick** [comment]
Thanks for pointing this out—it's due to https://github.com/w3c/ServiceWorker/issues/854.

That new behavior shipped in Firefox 52, and will ship in the upcoming Chrome 59 beta as well. I'll take care of adjusting the `sw-precache` logic to account for it.

**Comment by whmountains** [comment]
Thank you!

Will you publish a bugfix version immediately, or will I have to install directly from git until the next release comes out?

**Comment by jeffposnick** [comment]
I don't anticipate much of a delay in releasing this as `5.1.1` once the PR is merged.
