### ISSUE TITLE
[Snippet] Generate an appCache file based on the sw-precache config

### ISSUE THREAD

**Issue by whmountains** [GoogleChrome/sw-precache#293]
https://gist.github.com/whmountains/f477620b1336c51d6ab8150207466d13

I just made this and wanted to share it.  Maybe it will be useful for someone.

**Comment by bingo4508** [comment]
Why? It's a bit ironic for converting service worker to appCache... Are you trying to fallback if service worker is not supported by the browser?

**Comment by jeffposnick** [comment]
Thanks for the contribution, but support for the equivalent App Cache behavior is outside the scope of what we want to accomplish with this project.

**Comment by Poeticode** [comment]
Just wanted to say thanks for this snippet, @whmountains ! Apple devices don't support service workers (yet/ever), so I used this to fallback to AppCache to retain offline functionality.
