### ISSUE TITLE
Serve specified file from cache depending on current URL w/ function

### ISSUE THREAD

**Issue by plestik** [GoogleChrome/sw-precache#30]
Hi,

I have a web app with frontend routing. Every request which isn't for an asset (images/js/css etc) gets served the same index.html file. Is there any way for me to configure `sw-precache` to do this as well?

**Comment by jeffposnick** [comment]
Not as part of `sw-precache`, no, and I'd think that would be outside the scope of what we're looking to do with the project.

You can handle this scenario by defining an additional service worker `fetch` handler that will get executed before the built-in `sw-precache` `fetch` handler runs, and for certain requests returns, e.g., an `HTTP 301` response, with a `Location: /index.html` header. That way, your browser will end up firing off another request for `/index.html` (which will be handled by `sw-precache`) whenever there's a request made for another HTML page. Here's an (untested) example:

    // In sw-redirect.js:

    self.addEventListener('fetch', function(event) {
      var url = new URL(event.request.url);
      // Check to make sure that this isn't a request for /index.html, and that this is a HTTP GET for a HTML document.
      if (url.pathname !== '/index.html' && event.request.method === 'GET' && event.request.headers.get('accept').includes('text/html')) {
        var responseInit = {
          status: 301,
          statusText: 'Moved Permanently',
          headers: {
            Location: '/index.html'
          }
        };

        var redirectResponse = new Response('', responseInit);
        event.respondWith(redirectResponse);
      }
    });

    // In your build script:
    swPrecache.write(path.join(rootDir, 'service-worker.js'), {
      // ...other options...
      importScripts: ['sw-redirect.js']
    }, callback);

**Comment by plestik** [comment]
Thank you!
