### ISSUE TITLE
[question] I am using runtime caching for root page . am I doing it right ?

### ISSUE THREAD

**Issue by lili21** [GoogleChrome/sw-precache#303]
I am using `sw-precache-webpack-plugin`

```
...
plugins: [
  new SWPrecacheWebpackPlugin({
    ...
    runtimeCaching: [
      {
        urlPattern: /\/$/,
        handler: 'networkFirst'
      }
    ]
  })
]
```

It cached the root page, and works well. 
Will It be end with caching something that I am not expecting ? cause the `/\/$/` pattern can match any request , right ?

**Comment by jeffposnick** [comment]
If you're goal is to cache your HTML content, then you shouldn't have to set up `runtimeCaching` at all. By default, if Webpack knows about your HTML content, then it will automatically be precached, kept up to date, and served using a cache-first strategy.

What are you hoping to accomplish with `runtimeCaching`?

**Comment by lili21** [comment]
I am hoping user can get the latest content(index.html) as soon as possible. that's why I need network-first  rather then cache-first for the root page.

user has to refresh twice to get that when using a cache-first strategy for root page.first refreshing  for the latest service worker, and the second one for the index.html.

**Comment by jeffposnick** [comment]
I'd recommend not using `sw-precache` or precaching in general in that case.

You could use a library like [`sw-toolbox`](https://github.com/GoogleChrome/sw-toolbox) or the new [Workbox](https://workboxjs.org/) to implement runtime caching, and can set up routes to match whichever types of requests with your desired strategy (network-first, etc.) .

**Comment by adntin** [comment]
@jeffposnick I also want to cache the root path (/) at runtime. If the root path is cached at precache, there is no way to update it later.

<script>
    if(window.location.pathname === '/') {
      window.location.href = '/index.html';
    }
 </script>
