### ISSUE TITLE
question: index.html precaching—can I or must I?

### ISSUE THREAD

**Issue by englishextra** [GoogleChrome/sw-precache#308]
case:
```javascript
	staticFileGlobs: ["index.html"],
```
the app will open after refreshing/second entering the app root URL

case 2:
```javascript
	staticFileGlobs: [
// "index.html"
],
runtimeCaching: [{
			/^\/([^/]+\.html)$/,
// or /^\/index\.html$/,
			handler: "networkFirst",
			options: {
				debug: true
			}
		},
```
the app will NOT open after refreshing/second entering the app root URL

while when NOT using sw-precahe and just sw-toolbox:

```javascript
(function (global) {
	"use strict";
	/* Load the sw-toolbox library. */
	importScripts("./cdn/sw-toolbox/3.6.1/js/sw-toolbox.fixed.min.js");
	global.toolbox.options.debug = true;
	/* global.toolbox.precache(["","",""]); */
	global.toolbox.router.default = global.toolbox.networkFirst;
	/* Ensure that our service worker takes control of the page as soon as possible. */
	global.addEventListener("install", event => event.waitUntil(global.skipWaiting()));
	global.addEventListener("activate", event => event.waitUntil(global.clients.claim()));
})(self);
```

the app will open, yes performance would be slow when offline, and new requests that havn't done when online wont succeed,  that's OK.

So the question is:

Is it possible not to precache index.html with sw-precache and what would be the right dynamic runtimeCaching handler, so that the app should show. Thanks.

Why? Because if I precache index.html with sw-precache as in first piece of sw precache config or via gulp,
these assets and indx.html wont update if changes made even after several refreshments and new sw generating.

UPD Firefox 51.0/Chrome 59.0

**Comment by jeffposnick** [comment]
The main performance benefit that service workers offer comes from being able to serve your HTML  files cache-first. If you're not serving your HTML cache-first, then you still do have some benefits with regards to offline capabilities, but you lose much of the performance benefits.

So I'd encourage you to serve `index.html` cache-first. I'm not exactly sure why you can't—you mention

> Because if I precache index.html with sw-precache as in first piece of sw precache config or via gulp, these assets and indx.html wont update if changes made even after several refreshments and new sw generating.

which makes me think that perhaps you're serving your `service-worker.js` file with HTTP caching headers; see https://stackoverflow.com/questions/38843970/service-worker-javascript-update-frequency-every-24-hours/38854905#38854905 for a further explanation and best practices.

**Comment by englishextra** [comment]
@jeffposnick Yes, the cache headers. and the 24 hours stuff I read it. Dont like the idea to involve backend and am trying to work out a way in pure JS. The whole SW story would be nothing if index.html is not cacheFirst, and this makes almost impossible to update index.html content. Thanks. I read almost all you answers on SO, and they are nearly the only reliable and detailed on the web.
