### ISSUE TITLE
Ignore bower_components in staticFileGlobs

### ISSUE THREAD

**Issue by mbj36** [GoogleChrome/sw-precache#311]
Hi 
I have `bower_components` directory inside `app` ( `app` is my root directory ) and i am using `  staticFileGlobs: [
        rootDir + '/**/*.{js,html,css,scss,png,jpg,gif,svg,eot,ttf,woff,json}'
      ]` which also caches `bower_components` directory but i want to exclude that directory

I am trying this but this doesn't work 

`  staticFileGlobs: [
        rootDir + '/**/*.{js,html,css,scss,png,jpg,gif,svg,eot,ttf,woff,json}',
        rootDir + '/!bower_components{,/**/*}'
      ],`

**Comment by jeffposnick** [comment]
Tracked in #97
