### ISSUE TITLE
ng set apps.0.serviceworker=true not working

### ISSUE THREAD

**Issue by faveh** [GoogleChrome/sw-precache#319]
i tried using "ng set app.0.serviceworker=true" for the generation of the ngsw etc, but all i am getting is "can't add property  serviceworker, object is not extensible", please help me
![image](https://user-images.githubusercontent.com/9950920/27633381-d5ad26b6-5bf6-11e7-8b9f-a5094120e3dd.png)

**Comment by jeffposnick** [comment]
If you're experiencing an issue with Angular's `ngsw` tool, then https://github.com/angular/mobile-toolkit is the correct project to file it against. It's not related to `sw-precache`.
