### ISSUE TITLE
Delay caching static file globs

### ISSUE THREAD

**Issue by hsingh23** [GoogleChrome/sw-precache#321]
I have a couple of pdfs that I want to cache. I don't want to use runtime caching w/ cacheFirst strategy because the pdfs can change and I would like to update them when this happens w/o changing the file names (or adding hashes). 

Ideally I want to download the shell of my app with staticFileGlobs , and then download the pdfs after 5 or so seconds with **delayedStaticFileGlobs** that starts after a certain amount of time  specified in **delayTime** 

Thoughts?

**Comment by jeffposnick** [comment]
You can explicitly add entries ahead of time to a named cache via

```js
caches.open('pdfs').then(cache => cache.addAll([urlForPdf1, urlForPdf2, ...]);
```

This code can be run at any time, from either the client page or the service worker.

You can then set up a runtime caching rule to make use of that cache via something like

```js
{
  // Other sw-precache options...
  runtimeCaching: [{
    urlPattern: /\.pdf$/, // ...or whatever pattern you want
    handler: 'networkFirst', // ...or 'fastest', or any other handler name
    options: {cache: {name: 'pdfs'}}
  }]
}
```
