### ISSUE TITLE
iPhone Safari

### ISSUE THREAD

**Issue by sewarts** [GoogleChrome/sw-precache#327]
Using sw-precache and offline it works fine on every possible browser etc except iPhone Safari. All I can get on iPhone is:

Safari cannot open the page because your iPhone is not connected to the internet.

What to do?

**Comment by natecox** [comment]
Safari on iOS does not support service workers, so offline functionality is not possible there as far as I know.

**Comment by midzer** [comment]
Yeah, miserably it is not supported (yet) http://caniuse.com/#feat=serviceworkers

**Comment by sewarts** [comment]
Ok thanks.
