### ISSUE TITLE
Allow passing in a custom filesystem in options

### ISSUE THREAD

**Issue by callumlocke** [GoogleChrome/sw-precache#39]
Would you consider a PR that adds the ability to pass in a custom `fs` option?

sw-precache would still use `require('fs')` by default, but I could override this with a custom `fs` object that implements the same methods, such as [memory-fs](https://github.com/webpack/memory-fs).

This would allow me to use sw-precache as part of an in-memory pipeline of build steps – i.e. in situations where the files it's reading don't actually exist on disk; they only exist in memory, having been generated by prior build steps such as Babel and Browserify.

**Comment by jeffposnick** [comment]
If it's something you're finding useful in your own setup, then sure, I'd consider that kind of PR.

What's the advantage of running `sw-precache` against the resources while they're still in memory, before they're written to disk? Normally you'd run `sw-precache` once during your build and have it pick up every static resource that you care about, so I guess this makes sense if _everything_ is being run through `babelify` or the like, but it makes less sense if there are, e.g., some images that aren't part of the same pipeline.

**Comment by callumlocke** [comment]
> so I guess this makes sense if everything is being run through babelify or the like

Strange as it sounds, that is the situation :) I'm working on a [new build tool](https://github.com/exhibitjs/exhibit) that works the way you described – pushing *everything* through each step in the build sequence, which (perhaps surprisingly) leads to much faster builds.

For my sw-precache plugin, I ended up just importing your service-worker.tmpl and populating it myself, so I no longer need to be able to pass in a custom fs. I'm using it in a [fork of WSK](https://github.com/exhibitjs/exhibit-wsk) (which exists mainly to demo my new build tool) and it seems to work!

**Comment by jeffposnick** [comment]
Okay! Glad to see an ecosystem growing up around the service worker libraries :+1:
