### ISSUE TITLE
Error on dynamicUrlToDependencies

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/sw-precache#56]
I had the following config:

```js
swPrecache.write(path.join(GLOBAL.config.dest, 'sw.js'), {
    staticFileGlobs: [
      GLOBAL.config.dest + '/**/*.{js,html,css,png,jpg,jpeg,gif,svg}',
      GLOBAL.config.dest + '/manifest.json'
    ],
    dynamicUrlToDependencies: {
      '/app-shell': ['server/views/layouts/app-shell.handlebars'],
      '/api/': [
        'server/views/layouts/partial.handlebars',
        'server/views/index.handlebars'
      ],
      '/api/url-1': [
        'server/views/layouts/partial.handlebars',
        'server/views/url-1.handlebars'
      ],
      '/api/url-2': [
        'server/views/layouts/partial.handlebars',
        'server/views/url-2.handlebars'
      ]
    },
    stripPrefix: GLOBAL.config.dest,
    navigateFallback: '/app-shell',
    cacheId: packageName
  }).then(cb);
```

I deleted the partial.handlebars which caused the task to not finish (Gulp logs below):

[17:09:07] Finished 'scripts:es6' after 4.09 s
[17:09:07] Finished 'scripts' after 5.17 s
[17:09:07] Starting 'service-worker'...
$

Probably suggests two things:

1.) Have a catch handler on the promise in the docs
2.) Throw an error from swPrecache on this edge case

**Comment by jeffposnick** [comment]
Can you try the same steps again against the `master` branch? I'm pretty sure this was reported in #43 and fixed in https://github.com/GoogleChrome/sw-precache/commit/4ea2357e113b852e343720f1bfb2bbdc26bbbace but I haven't pushed a release that contains that fix to `npm` yet.

Now that the Chrome Dev Summit is over I'll push a patch release if you can confirm that it resolves your issue.

**Comment by gauntface** [comment]
I've tried recreating the problem in a test case, in PR https://github.com/GoogleChrome/sw-precache/pull/58

**Comment by jeffposnick** [comment]
PR #58 primarily focused on adding in a test case (which is great!) but didn't seem to change any logic. Can you confirm that the code change in https://github.com/GoogleChrome/sw-precache/commit/4ea2357e113b852e343720f1bfb2bbdc26bbbace was sufficient?
