### ISSUE TITLE
Add ability to name service-worker.js something different

### ISSUE THREAD

**Issue by owencm** [GoogleChrome/sw-precache#77]
[Low priority feature request]

I'd like to import the generated sw-precache SW into my existing SW, which is already named service-worker.js so it would be nice to have an option to control the name.

I know I could do the reverse and import my actual SW into the sw-precache one but for various reasons I'd rather not.

**Comment by jeffposnick** [comment]
Hello @owencm—The first parameter to [`write()`](https://github.com/GoogleChrome/sw-precache#writefilepath-options-callback) is `filePath`, which is a path + filename to the generated SW file. You can use whatever you'd like for the filename portion.

I'd recommend doing things the other way around, though, and use [`importScripts`](https://github.com/GoogleChrome/sw-precache#importscripts-arraystring) to include your extra SW logic. `sw-precache` works by triggering the SW update flow whenever there are changes to any files that it tracks, and implies that the file passed to `navigator.serviceWorker.register()` is the file that `sw-precache` generates.

If you really, really can't use `sw-precache`'s output as the registered SW file, then as of right now, something like [`gulp-rev`](https://github.com/sindresorhus/gulp-rev) would be needed to change the file name of the `sw-precache` output, and then the update to the filename in your `importScripts()` call would trigger the SW update flow.

**Comment by owencm** [comment]
Thanks for the explanation. I'm trying to work out how a developer would use this in conjunction with other autogenerated SWs for push etc, but it seems for the short term having sw-precache as the head makes sense given its taking care of caching.

**Comment by jeffposnick** [comment]
Yeah, assuming there's nothing special that the other auto-generated SWs need to do in terms of triggering the SW update flow, I think just passing in their paths to [`importScripts`](https://github.com/GoogleChrome/sw-precache#importscripts-arraystring) should work as expected. I'd be interested in hearing if there's a concrete reason why this wouldn't be the case.
