### ISSUE TITLE
Possible to use a single cache?

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/sw-precache#86]
Chatting with one of the engineers and the topic of using multiple caches (i.e. one per asset) could be poor in terms of the number of instances of caches in memory at any one time.

Is there a specific reason precache couldn't use a single cache?

**Comment by pb6110** [comment]
im not sure

**Comment by jeffposnick** [comment]
I had informally run the idea of multiple caches by some of the Chrome engineers during initial development, and there weren't any red flags raised at the time. But I wouldn't be surprised if there are yellow flags, and it's admittedly an ugly hack that I'd rather avoid.

When `sw-precache` launched, I recall that there wasn't native support for `cache.match()`, and the polyfill was O(N), which made the performance poor in some early experimentations that used a single cache with a large set of resources. That's not an issue anymore.

More of an issue now is the best way to store the MD5 fingerprint metadata as part of a `Request` object's URL. We could synthesize a new `Request` object and append a URL parameter like `sw-precache-fingerprint=<MD5>` to the real URL without too much of a risk of breakage, I think, but it's not a trivial change, and it wouldn't be backwards compatible with any previous cache entries. But it seems like a viable solution, unless anyone has other ideas.

See https://github.com/slightlyoff/ServiceWorker/issues/657#issuecomment-151866195 for some related discussion of storing metadata for cache entries.

**Comment by jkarlin** [comment]
cache.match() is fast now, but operations on a single cache run sequentially (there is a todo to make this parallel where possible) so it's possible you'll see performance degradation compared to lots of caches running in parallel

**Comment by gauntface** [comment]
Counter argument to that: at the moment sw-precache has to intercept the
fetch request and find the correct cache first.

**Comment by jeffposnick** [comment]
Finding the correct cache is done via an in-memory `Object` mapping that should complete quickly and synchronously, though.

**Comment by jkarlin** [comment]
I think you should use a single cache. And then complain if the performance degrades :)
