### ISSUE TITLE
Notify which assets have updated

### ISSUE THREAD

**Issue by mbrevda** [GoogleChrome/sw-precache#88]
Is there someway to be notified of which assets have been updated? For example, if a new stylesheet came in, using postMessage we can get its path, and update the src of the current stylesheet  - avoiding a reload. If api data was refreshed we can pass this to our data layer via postMessage without ever notifying the user or requiring a refresh. Obviously there are some cases where the hassel isnt warranted, but likewise, there are plenty of cases where a full refresh is an overkill and a bad ux.

**Comment by jeffposnick** [comment]
This would be a good functionality to add, yes.

It's tracked at https://github.com/GoogleChrome/sw-precache/issues/47

**Comment by mbrevda** [comment]
thanks, sorry for the dup
