### ISSUE TITLE
Investigate partial cache busting and content updated

### ISSUE THREAD

**Issue by mkhatib** [GoogleChrome/sw-precache#89]
As [described on stackoverflow](http://stackoverflow.com/questions/35596881/does-sw-precache-activation-of-new-service-worker-guarantees-cache-busting/). What appears to be partial cache updates break the site trying to load no longer existant assets version (neither in SW cache nor remotely).

index.html has the same hash value in two different browsers caches but with two different content.

[Gruntfile](https://github.com/manshar/manshar/blob/master/web-client/Gruntfile.js#L535) generating the sw-precache service worker.

A gist for the [service-worker.js generated by that task](https://gist.github.com/mkhatib/1d812451fc1dcd1ac051).

**Comment by jeffposnick** [comment]
I've spent some time today trying to reproduce what you're seeing, but am not having any luck. I've been going against the example at https://github.com/manshar/manshar and confirm that going through the Grunt build process, updating a local asset, and then going through the build process again results in updates to the bundled modules, the index.html, and the hash codes associated with each resource in the service-worker.js file.

When `sw-precache` fetches an updated resource as part of its install handler, it [uses cache-busting](https://github.com/GoogleChrome/sw-precache/blob/master/service-worker.tmpl#L73) to ensure that a fresh copy of the updated resource is retrieved from the network. Is it possible that your web server (or proxy server) is configured in a way that would result in a stale copy of `index.html` being returned in spite of the differing URL parameters?

Also, have you been able to reproduce getting into this state on multiple browser instances, or has it been a one-time thing?

**Comment by jeffposnick** [comment]
I'm closing this for now. Please ping the issue if you can reproduce.
