### ISSUE TITLE
intercept all non-extension requests and send index.html for an html5-routed web app

### ISSUE THREAD

**Issue by aeharding** [GoogleChrome/sw-precache#91]
Hello everyone, thanks for your work on this project. I'm using it in creating my side project, [financier](https://github.com/aeharding/financier), an Angular 1, PouchDB offline webapp.

I'm curious how you guys would approach html5 routing in a best practice with sw-precache. My google-fu is not showing anyone else that has encountered this before.

For example, I cache `index.html`, and then this allows navigating to `example.com/` to work. However, `example.com/an-html5-route` doesn't load `index.html`, like it does in a traditional, properly configured server.

What is the best way to intercept all requests without an extension and send them index.html?

The equivalent functionality in express:
```js
// define other request handlers above this
app.all('/*', function(req, res) {
  res.sendfile('index.html');
});
```

If this isn't really an issue for sw-precache, feel free to close this and point me in the right direction. :)

Thanks!

**Comment by jeffposnick** [comment]
This has been coming up more and more recently, so it points to an area that our existing documentation could explain more clearly. (CC: @jpmedley)

What you're suggesting is accomplished via the [`navigateFallback`](https://github.com/GoogleChrome/sw-precache#navigatefallback-string) option, which lets you define a "fallback" URL for your App Shell that's used to fulfill navigations that don't match anything already in the cache. (You can combine it with the [`navigateFallbackWhitelist`](https://github.com/GoogleChrome/sw-precache#navigatefallbackwhitelist-arrayregexp) option if you want only certain URL patterns to fall back to the App Shell HTML document.)

```js
{
  navigateFallback: '/index.html',
  navigateFallbackWhitelist: [regex1, regex2] // Optional, to whitelist URL patterns to map to /index.html
  // Other sw-precache options.
}
```

The [app-shell-demo](https://github.com/GoogleChrome/sw-precache/tree/master/app-shell-demo) directory has an example of a working configuration for a React-based SPA, and there are some additional details about that demo in [this video](https://www.youtube.com/watch?v=jCKZDTtUA2A).

I'm closing this issue for now, but feel free to reopen this, or open a new issue, if you have any further questions.

**Comment by aeharding** [comment]
Excellent! Thank you for pointing that out -- I should have just looked closer.

If it's any help, the main keywords I was looking for were `html5 mode` and `routing` with `sw-precache`, due to the prevalent angular 1 code:

```js
$locationProvider.html5Mode(true);
```

Another thing I might google would be `404 page` or `404 fallback` with `sw-precache`.

Just in case you decide to beef up the documentation :wheelchair:.

**Comment by jcdesousa** [comment]
Hi, i have the same when to https://example.com/an-html5-route it does not load the index.html. 

I added the `navigateFallback: '/index.html'`, maybe is because of the service worker scope. When i go to Application -> Service Workers. it's not installed.

Everything is fine  with https://example.com.

**Comment by jeffposnick** [comment]
If your SW isn't installed then yes, that would certainly be a problem.

I'd appreciate it if you could open a new issue if you run into what appears to be a bug in `sw-precache` that is preventing the SW it generates from being properly installed.
