### ISSUE TITLE
Missing sw-toolbox source map when inlining sw-toolbox

### ISSUE THREAD

**Issue by playground** [GoogleChrome/sw-precache#93]
Looks like the latest Chrome Version 49.0.2623.75 has caused 

GET http://localhost:8009/service-worker.js net::ERR_FILE_EXISTS, service worker failed to load every time.

And also caused Failed to parse SourceMap: http://localhost:8009/sw-toolbox.map.json
To get rid of the parse error, I had to change sourceMappingURL in the generated service-worker.js
from
//# sourceMappingURL=sw-toolbox.map.json
to
//# sourceMappingURL=node_modules/sw-toolbox/sw-toolbox.map.json

This was all working up until this morning.with version 48  

Thanks.

**Comment by jeffposnick** [comment]
The `net::ERR_FILE_EXISTS` is a [bug in Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=541797), the fix for which will roll out with Chrome 50. It's harmless noise in the meantime.

Regarding the source map, yes, we should either omit the `sourceMappingURL` line when inlining `sw-toolbox` or alternatively find some way of including it, though forcing folks to copy over an additional file prior to deploying their service worker might not be very friendly.

**Comment by playground** [comment]
Thanks Jeff,

The question is when I was on Version 48.0.2564.116 (64-bit).  I didn't get those errors and pre-cache was doing what it was supposed to.  When Chrome got upgraded to Version 49.0.2623.75 (64-bit)
seems like the pre-cache isn't working anymore as if the requests are being made across the network.  Here is the screenshot.

![image](https://cloud.githubusercontent.com/assets/243495/13574577/b5179e8a-e452-11e5-8bc3-a877e108850b.png)

**Comment by playground** [comment]
BTW, looks like websocket connection is also failing for browser-sync

![image](https://cloud.githubusercontent.com/assets/243495/13575950/4e91f302-e459-11e5-81d5-f418f61461a8.png)

**Comment by agungsb** [comment]
I get the same error while developing in localhost environment. In Chrome Dev Tools, if I go to Applications and click Service Workers and update Service Worker, I see the following error message:

![screen shot 2016-08-29 at 4 06 19 pm](https://cloud.githubusercontent.com/assets/5051832/18046573/b5f89a54-6e02-11e6-8564-f9d306999dfb.png)

Any thoughts?

**Comment by jeffposnick** [comment]
@agungsb, this is a closed issue used to track a message about a missing sourcemap. If you're seeing an unrelated problem with `sw-precache`, could you create a new issue in the track it? It would help if you provided, along with the screenshot in this thread, information about whether you see the failure for the initial SW installation, or whether you only get that error when "Upload on Reload" is checked and you click "Update".
