### ISSUE TITLE
Advanced App Shell routing

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/sw-precache#94]
The current release of `sw-precache` has a very rudimentary "routing" system in place, in which navigations to either all URLs or just URLs that match a set of `RegExp`s will result in the App Shell HTML, via the `navigateFallback` and `navigateFallbackWhitelist` options.

This works well enough for sites that only have a single App Shell within the scope of their service worker, but it would break down when there are multiple App Shells that might be used for different URL routes.

Something more flexible allowing arbitrary route-to-App Shell mappings would allow for more complicated web app setups.

And then it may or may not make sense to combine this routing with the routing rules used to define `sw-toolbox` runtime caching via the `runtimeCaching` option.

CC: @addyosmani @gauntface @wibblymat for thoughts.

**Comment by mickeywu** [comment]
@jeffposnick Any plans to implement this in upcoming versions?

**Comment by jeffposnick** [comment]
No, I should probably close this.

It's going to be much easier to do this as part of the [`sw-helpers`](https://github.com/GoogleChrome/sw-helpers) project, which has a flexible [`sw-routing`](https://github.com/GoogleChrome/sw-helpers/tree/master/packages/sw-routing) library under the hood.
