### ISSUE TITLE
WebKit url.search adds an extra '?'

### ISSUE THREAD

**Issue by arbesfeld** [GoogleChrome/sw-precache#99]
In WebKit this line: https://github.com/GoogleChrome/sw-precache/blob/3.1.0/lib/functions.js#L27

Causes an extra `?` to be added to the url when the right-hand result is an empty string. This causes `sw-precache` to fail in Safari.

You can reproduce this behavior by going into the Safari console and running:

```
var url = new URL('https://google.com')
url.search = '';
url.toString();
```

The result will be a string `https://google.com/?`;

I'd like to submit a PR that changes the behavior to assign `url.search = null` rather than an empty string.

**Comment by jeffposnick** [comment]
As per item 6 of https://url.spec.whatwg.org/#url-serializing, it sounds like what Safari is doing follows the spec (while Chrome isn't), so sure, that sounds like a reasonable change and a PR would be welcome.

But... I feel compelled to ask, given the lack of service worker support in Safari, how did you come across this issue?

**Comment by arbesfeld** [comment]
Great! PR will be forthcoming.

I've been thinking about adding Service Worker support to Cordova and ran across this issue. Also... I feel compelled to ask... do you think Chrome iOS could support Service Worker at some point?

**Comment by jeffposnick** [comment]
I'm revisiting some old issues, and looking into this again.

Setting `URL.search` to `null` will actually not have the intended effect in Chrome or Firefox—it will cause the serialized URL to end with `?null`.

Moreover, the current Safari Technology Preview (release 12 (Safari 9.1.2, WebKit 11603.1.3)) matches Chrome and Firefox's behavior, which makes me think that even though the stable release of Safari would behave as you intend when using `null`, it will stop working in the future (and break Chrome/Firefox in the present).

As far as I can tell, there's *no* way to clear our `URL.search` in the Safari Technology Preview, but I'm going to assume that they'll standardize on Chrome/Firefox's behavior, and accept `''` prior to the official release.

You can try out https://jsbin.com/tilopiy/edit?js,console in a few different browsers.
